### ISSUE TITLE
Balises fermantes supprimées par Lodel

### ISSUE THREAD

**Issue by brrd** [OpenEdition/checklist-lodel#1]
Dans le contexte des publications, checklist a besoin de générer une représentation de la table des matières dans un objet javascript. Le template utilise actuellement cette approche : https://github.com/OpenEdition/checklist-lodel/blob/8dc93ae8bbc61983c7a0056f4428c149668aeeb3/tpl/macros_checklist_publication.html#L61-L80

Le résultat est inclus dans une balise script de la page HTML du template.

Le souci, c'est que quand toutes les balises fermantes contenues dans l'objet généré sont supprimées par Lodel.

Exemple :

```javascript
{
  title: "<span class='authors'>Jean-Michel Bu&eacute;e                   <span class='title'><span xml:lang=&quot;fr&quot; lang=&quot;fr&quot;>La vraie d&eacute;mocratie et la question de la critique du lib&eacute;ralisme politique dans le <em>Manuscrit de Kreuznach de Marx",
  href: "./?do=_checklist_view&document=318",
  docId: "318",
  type: "Article",
  context: {
    "textes": true,
    "article": true
  }
}
```

dans http://checklist.labocleo.org/test/?do=_checklist_view&document=310

On voit ici que les balises fermantes des éléments `<span>` et `<em>` ont été supprimées, ce qui pose des problèmes lors du rendu.

Je précise que wapper le tout dans des CDATA ne change rien au résultat.

D'où vient ce problème (HTMLPurifier ?) ? Comment le résoudre ?

**Comment by brrd** [comment]
J'ai fait quelques tests supplémentaires (suggérés par @nahuelange et @arnaudcordier) et voici plusieurs précisions.

**1\. Remplacer la variable par une string codée directement dans la source confirme que le souci ne vient pas du template mais d'un traitement effectué après.**

Ceci codé dans la source :

```
title: "<span>hello world <em>ital ici</em> mais pas la</span>",
```

donne l'affichage suivant :

```
title: "<span>hello world <em>ital ici mais pas la;",
```

Il s'agit donc à coup sûr d'un problème de post-traitement.

**2\. Nous ne reproduisons pas le problème sur les sites edinum.**

En prenant par exemple un article dont le titre renseigné est `<span>hello world <em>ital ici</em> mais pas la</span>`

Cléo :

```
title: "<span class='authors'>Jean-Michel Bu&eacute;e <span class='title'><span>hello world <em>ital ici mais pas la",
```

Edinum : 

```
title: "<span class='authors'>Marcus Valerius Martialis</span> <span class='title'><span>hello world <em>ital ici</em> mais pas la</span></span>",
```

En conclusion il semble donc que le problème ne vient pas de Checklist ni même de Lodel mais d'un traitement effectué spécifiquement sur vos sites @lnprieto

**Comment by brrd** [comment]
@lnprieto :

> J'ai installér checklist sur différentes vms, avec le même résultat. Je voudrais l'installer maintenant sur une version publique de lodel, mais il a besoin de lodel-common. Sur tes essais edinum, tu as installé lodel-common ? 

Non. Nous avons notre propre lodel-common pour Edinum.

> si non comment as-tu géré les fonction Media ?

Ce filtre a été réécrit.
Je ne pense pas que cela vienne du filtre media car il n'est pas appelé dans le template où l'on rencontre le bug. Tous les filtres utilisés sur ce template sont dans https://github.com/OpenEdition/checklist-lodel/blob/master/tpl/macros_checklist_publication.html

**Comment by lnprieto** [comment]
Non je ne pense pas non plus que cela vienne du filtre, mais je voulais être sûre que vous n'aviez pas installé notre lodel-common. 
Merci

**Comment by brrd** [comment]
Pour info Arnaud vient de publier le lodel-common d'edinum sur Github : https://github.com/edinum/lodel-textfunc

**Comment by lnprieto** [comment]
OK merci
Sur ma vm, réduite au minimum, sans lodel-common, les balises fermantes sont toujours absentes, et on a un serveur de dev, avec lodel-common, sur lequel cela fonctionne correctement.
Donc clairement, ça ne vient pas lodel-common
A suivre

**Comment by 3th0** [comment]
Si l'on supprime les balises <script> dans le template macros_checklist.html : 
```
diff --git a/tpl/macros_checklist.html b/tpl/macros_checklist.html
index 7fb272b..d3336ef 100644
--- a/tpl/macros_checklist.html
+++ b/tpl/macros_checklist.html
@@ -144,11 +144,9 @@
   <!-- Checklist -->
   <script src="[#SHAREDIR]/plugins/custom/checklist/node_modules/@openedition/checklist/dist/checklist.js"></script>
   <script src="[#SHAREDIR]/plugins/custom/checklist/public/js/checklist-config.js"></script>
-  <script>
     $(function () {
       window.initChecklist("[#SITE]", [#DOCUMENT], [%CHECKLIST_CONTEXT], [%CHECKLIST_PUBLI]);
     });
-  </script>
 </DEFMACRO>
```

les balises HTML fermantes sont bien présente donc c'est surement un traitement lodel qui fait de la suppression à l'intérieur des balises scripts. 
Les pistes : 
* htmlpurifier (vérifier fonctionnement (github) + version (celle openedition + edinum)) 
* parser lodelscript 

Nous arrivons à reproduire le problème sur l'edt-journals mais pas sur la vm dédiée checklist.

**Comment by jfriviere** [comment]
Vous pouvez tester de supprimer l'indentation du template par le parser lodelscript (au cas où) en remplaçant ici :
https://github.com/OpenEdition/checklist-lodel/blob/master/tpl/checklist.html
```
<CONTENT VERSION="1.0" LANG="fr" CHARSET="utf-8"/>
```
par 
```
<CONTENT VERSION="1.0" LANG="fr" CHARSET="utf-8" NOINDENT="1"/>
```

**Comment by jfriviere** [comment]
Je reproduis en fait le problème sur up10/journals. C'est plus facile pour tester.

L'ajout de NOINDENT ne change rien.

Par contre, ce hack a l'air de fonctionner. Mais c'est pas très beau et il peut surement poser des problèmes selon les navigateurs.

```
diff --git a/tpl/macros_checklist.html b/tpl/macros_checklist.html
index 7fb272b..c6b8806 100644
--- a/tpl/macros_checklist.html
+++ b/tpl/macros_checklist.html
@@ -146,7 +146,7 @@
   <script src="[#SHAREDIR]/plugins/custom/checklist/public/js/checklist-config.js"></script>
   <script>
     $(function () {
-      window.initChecklist("[#SITE]", [#DOCUMENT], [%CHECKLIST_CONTEXT], [%CHECKLIST_PUBLI]);
+      window.initChecklist("[#SITE]", [#DOCUMENT], [%CHECKLIST_CONTEXT], [%CHECKLIST_PUBLI|replace('</','<\/')]);
     });
   </script>
 </DEFMACRO>
```

**Comment by brrd** [comment]
Mardi dernier en réunion de travail nous avons constaté que le problème était résolu sur la VM. Sur cette page par exemple, tout fonctionne bien maintenant : http://checklist.labocleo.org/test/?do=_checklist_view&document=310&clearcache=oui
C'est pourtant ici que j'avais constaté le problème pour la première fois. Une modif a donc sans doute a été faite entre temps et résolu le problème. Reste à savoir laquelle...

@jfriviere :

> Par contre, ce hack a l'air de fonctionner. Mais c'est pas très beau et il peut surement poser des problèmes selon les navigateurs.

C'est assez surprenant oui, mais je ne pense pas que cela ait des comportements différents selon les navigateurs : la chaîne est envoyée et parsée par jQuery qui a l'intérêt de tout normaliser. Autrement dit si ça marche dans un navigateur ça devrait marcher partout. C'est donc un fix qu'on peut à mon avis envisager faute de mieux.

Je l'intègre à checklist ?

**Comment by amandine-texier** [comment]
Le problème ne se pose plus, que ce soit sur la VM (http://checklist.labocleo.org/test/?do=_checklist_view&document=310), sur l'EDT (https://edt-journals.openedition.org/equipe-revues/?do=_checklist_view&document=3635) ou sur la prod (https://journals.openedition.org/viatourism/?do=_checklist_view&document=2885), je clos le ticket
