### ISSUE TITLE
Template article : style des tableaux non affiché

### ISSUE THREAD

**Issue by amandine-texier** [OpenEdition/checklist-lodel#10]
Dans le template article, chaque style de paragraphe est affiché ("texte", "citation", etc.), y compris pour les illustrations mais pas pour les tableaux (cf. http://checklist.labocleo.org/test/?do=_checklist_view&document=354 §5), est-ce un bug ou bien volontaire (si par exemple les styles s'affichaient sur chaque cellule, ce qui n'est peut-être pas souhaitable) ?

**Comment by brrd** [comment]
C'est parce qu'en HTML les tableaux ne sont pas contenus dans des paragraphes. Les `<p>` se trouvent à l'intérieur des cellules, donc s'il faut les afficher c'est effectivement dans les cellules.
Dis-moi si tu veux que je les ajoute dans les cellules.

**Comment by amandine-texier** [comment]
Je m'en doutais, du coup on va laisser ainsi sinon je crains que ça fasse trop de bruit, merci !
