### ISSUE TITLE
Test images:existence ne se déclenche pas partout

### ISSUE THREAD

**Issue by amandine-texier** [OpenEdition/checklist-lodel#100]
En faisant le point sur les nouveaux tests à implémenter pour Books, je remarque que le test images:existence concernant les images qui ne s'affichent pas, déjà implémenté sur Journals, ne se déclenche pas dans certains cas, cf. http://checklist.labocleo.org/test/?do=_checklist_view&document=982 paragraphes 49 et 68 ou encore http://checklist.labocleo.org/test/?do=_checklist_view&document=75 paragraphe 18

Les deux documents ont été chargés en XML, peut-être que l'absence d'alerte vient de là ? Mais je me demande si c'est pas un effet de bord, parce que http://checklist.labocleo.org/test/?do=_checklist_view&document=75 était dans les URL de tests pour cette règle donc j'imagine qu'il a fonctionné dessus à un moment donné

Le test fonctionne toujours bien là : http://checklist.labocleo.org/test/?do=_checklist_view&document=322

**Comment by brrd** [comment]
C'est parce que ces deux situations n'ont pas été prévues lors de l'écriture initiale du test.

Dans le premier cas, il s'agit d'une image au format psd, or à ce jour checklist ne cherche que les jpg (vu que Lodel est censé faire la conversion avant l'affichage) : https://github.com/OpenEdition/checklist-lodel/blob/e9e3682a152eccda058a5491e7bcab6ba381bffa/tpl/macros_checklist_article.html#L326

Dans le deuxième cas, c'est une image dans un format non supporté (wmf), qui normalement devrait être signalée comme "image non convertie" par Lodel avec une classe "image_error" (voir [ici](https://github.com/OpenEdition/lodel/blob/be000e911180824c0a521c8f1b940cea27a630ad/lodel/scripts/logic/class.entities_import.php#L206)), mais pour une raison que je n'explique pas ce n'est pas le cas ici.

Le problème est que Lodel ne gère pas toutes les erreurs de la même façon, et donc qu'il faut qu'on s'adapte à tous les cas de figure sans exactement pouvoir les lister avec certitude. Dans le cas présent je vais essayer de vérifier toutes les extensions d'images (pas juste jpg), ce qui règlera peut-être le problème.

**Comment by brrd** [comment]
@amandine-texier Pourrais-tu m'indiquer les extensions d'images qui sont acceptées dans le texte stp ? 

jpg, jpeg, png, gif ?

svg, bmp et webp sont aussi acceptés par la plupart des navigateurs. Faut-il les ajouter à la liste ?

**Comment by amandine-texier** [comment]
Les extensions d'images acceptées dans le texte sont : jpg, jpeg, png, gif, svg

bpm et webp sont malheureusement pas géré dans notre chaîne (Lodel / PDF / archivage).

> De cette façon la stratégie serait : 1) vérifier que l'extension est valide sinon erreur, 2) si oui, vérifier l'existence du fichier image sur le serveur.

Superbe, merci

**Comment by brrd** [comment]
C'est corrigé sur les deux VM. 
@amandine-texier je te laisse vérifier que tout fonctionne comme vous voulez et fermer ce ticket si c'est bon.

**Comment by amandine-texier** [comment]
C'est parfait merci !
