### ISSUE TITLE
Modifications de la home

### ISSUE THREAD

**Issue by amandine-texier** [OpenEdition/checklist-lodel#103]
Suite aux discussions et retours des collègues, voici quelques demandes de modifications sur la home valables pour **OEB et OEJ**.

Il faudrait mettre en place un filtre dans l'onglet "Publications" qui permettrait de filtrer selon le statut : publié [qui inclurait "protégé"] et prêt à publier [qui inclurait "brouillon"] si possible. Si ces regroupements ne sont pas possibles, un filtre publié / prêt à publier / protégé / brouillon sera très bien aussi.

Est-ce qu'on peut ordonner l'onglet "Publications" par ordre antéchronologique selon la date de mise en ligne ?

Pour l'onglet "Export CSV", notre œil de lynx en interne nous signale une erreur orthotypo sur "Afficher les erreurs d’**é**xécution avec l’état "error"." où ce devrait être "exécution".

Est-ce qu'il serait envisageable d'ajouter un filtre à cet export de type "Afficher seulement les publications non publiées" (qui comprendrait brouillon + prêt à publier) ?

**Comment by brrd** [comment]
> Il faudrait mettre en place un filtre dans l'onglet "Publications" qui permettrait de filtrer selon le statut : publié [qui inclurait "protégé"] et prêt à publier [qui inclurait "brouillon"] si possible. Si ces regroupements ne sont pas possibles, un filtre publié / prêt à publier / protégé / brouillon sera très bien aussi.

C'est fait.

> Est-ce qu'on peut ordonner l'onglet "Publications" par ordre antéchronologique selon la date de mise en ligne ?

Voir #103.

> Pour l'onglet "Export CSV", notre œil de lynx en interne nous signale une erreur orthotypo sur "Afficher les erreurs d’éxécution avec l’état "error"." où ce devrait être "exécution".

C'est corrigé.

> Est-ce qu'il serait envisageable d'ajouter un filtre à cet export de type "Afficher seulement les publications non publiées" (qui comprendrait brouillon + prêt à publier) ?

C'est fait (sur la VM books pour l'instant). J'ai plutôt utilisé le libellé "Ignorer les publications publiées." qui à mon avis décrit mieux ce qui se passe du point de vue de l'exécution de Checklist.

Je ferme ce ticket. Merci d'en rouvrir des spécifiques si besoin de modifier certaines choses.
