### ISSUE TITLE
Ordre des publications sur la home

### ISSUE THREAD

**Issue by brrd** [OpenEdition/checklist-lodel#107]
#103 : 

> Est-ce qu'on peut ordonner l'onglet "Publications" par ordre antéchronologique selon la date de mise en ligne ?

Le champ datemisenligne n'existe que pour les entités publiées. Pour toutes les autres il est vide. Il n'est donc peut-être pas approprié ici.

Deux autres champs sont disponibles pour toutes les entités :

* creationdate
* modificationdate

Lequel faut-il utiliser ?

**Comment by amandine-texier** [comment]
Utiliser le champ creationdate serait parfait

**Comment by brrd** [comment]
Fait sur la VM books.
