### ISSUE TITLE
Titre des menus contextuel

### ISSUE THREAD

**Issue by brrd** [OpenEdition/checklist-lodel#108]
Actuellement le menu contextuel des documents est nommé "Options", or il s'agit plutôt d'un menu de "navigation" ou de "liens". Il me semble aussi que cela créé la confusion avec le menu des préférences, dont l'icône est située juste à côté dans la barre latérale de Checklist.
Il est également possible d'ajouter une icône pour ce menu.

**Comment by amandine-texier** [comment]
Après discussion, "Fonctions" serait parfait pour renommer le menu contextuel des documents, sans ajouter d'icône, merci !
