### ISSUE TITLE
Poids de fac-similé articles trop important : faux positifs

### ISSUE THREAD

**Issue by amandine-texier** [OpenEdition/checklist-lodel#11]
Le test facsimile:quality(filesize)[textes] présente des faux positifs sur les unités documentaires suivantes, alors que le poids est inférieur à 10 Mo : 
- http://checklist.labocleo.org/test/?do=_checklist_view&document=354 (163 ko) ;
- http://checklist.labocleo.org/test/?do=_checklist_view&document=497 (61 ko).

**Comment by brrd** [comment]
J'ai aussi corrigé au passage le même test pour les publications (facsimile:quality(filesize)[publications]).
