### ISSUE TITLE
Données manquantes dans les exports CSV

### ISSUE THREAD

**Issue by amandine-texier** [OpenEdition/checklist-lodel#114]
Plusieurs règles positives sur Checklist ne sont pas récupérées dans les exports CSV :

- souspartie:quality : https://books-devel.labocleo.org/africae/?do=_checklist_view&document=2398 et http://checklist.labocleo.org/test/?do=_checklist_view&document=1208
- facsimile:quality(filesize)[publications] : https://books-devel.labocleo.org/africae/?do=_checklist_view&document=2400 mais OK sur Journals http://checklist.labocleo.org/test/?do=_checklist_view&document=74
- facsimile:quality(filesize)[textes] : https://books-devel.labocleo.org/africae/?do=_checklist_view&document=2434 mais OK sur Journals http://checklist.labocleo.org/test/?do=_checklist_view&document=803
- numeroouvert:quality(historique) qui existe seulement sur OEJ : http://checklist.labocleo.org/test/?do=_checklist_view&document=376 

De plus, sur OEB, il semblerait que les documents de type "annexes" ne sont pas récupérés non plus dans les exports, exemples : https://books-devel.labocleo.org/africae/?do=_checklist_view&document=2647 & https://books-devel.labocleo.org/africae/?do=_checklist_view&document=2658

**Comment by brrd** [comment]
Bravo @amandine-texier pour la détection de ces problèmes, c'est très bien vu.

* [ ] souspartie:quality : https://books-devel.labocleo.org/africae/?do=_checklist_view&document=2398 et http://checklist.labocleo.org/test/?do=_checklist_view&document=1208

Problème : ce test repose en front sur l'exécution préalable du JS du noyau de Checklist dans le template, ce qui n'est pas le cas lors de l'export CSV.

```js
var $bad = $(".checklist-toc-section-contents .checklist-toc-section-contents:empty");
```

TODO : il faut plutôt tester ça en Lodelscript.

* [x] facsimile:quality(filesize)[publications] : https://books-devel.labocleo.org/africae/?do=_checklist_view&document=2400 mais OK sur Journals http://checklist.labocleo.org/test/?do=_checklist_view&document=74

Le problème vient de la condition "ocr" qui ne se trouve pas dans le contexte lorsque celui-ci est généré pour le batch dans https://books-devel.labocleo.org/africae/?do=_checklist_get&documents=2400

Résolu en corrigeant CKL_CREATE_CONTEXT_JSON.

* [x] facsimile:quality(filesize)[textes] : https://books-devel.labocleo.org/africae/?do=_checklist_view&document=2434 mais OK sur Journals http://checklist.labocleo.org/test/?do=_checklist_view&document=803

Idem.

* [x] numeroouvert:quality(historique) qui existe seulement sur OEJ : http://checklist.labocleo.org/test/?do=_checklist_view&document=376

Idem.

* [x] De plus, sur OEB, il semblerait que les documents de type "annexes" ne sont pas récupérés non plus dans les exports, exemples : https://books-devel.labocleo.org/africae/?do=_checklist_view&document=2647 & https://books-devel.labocleo.org/africae/?do=_checklist_view&document=2658

Ah oui, il y avait bien la condition `type NOT LIKE '%annexe%'` pour éviter de récupérer les fichiers annexes. Je remplace par une condition sur la classe qui devrait faire l'affaire.

**Comment by brrd** [comment]
Normalement tout est résolu sur OEJ et OEB.
