### ISSUE TITLE
Modifier règle titreillustration:quality(position)

### ISSUE THREAD

**Issue by amandine-texier** [OpenEdition/checklist-lodel#117]
Est-ce possible de modifier la règle titreillustration:quality(position) pour étendre son principe aux légendes et crédits d'illustration ? Il faudrait donc la déclencher également si dans le document : 

- un paragraphe légende d'illustration n'est pas précédé d'une image, d'un tableau, d'un embed média
- un paragraphe crédits d'illustration n'est pas précédé d'une image, d'un tableau, d'un embed média _ou_ d'un paragraphe légende d'illustration

Exemples : 
- https://books-devel.labocleo.org/africae/?do=_checklist_view&document=2633 & http://checklist.labocleo.org/test/?do=_checklist_view&document=1285 paragraphe 5 crédit d'illustration seul
- https://books-devel.labocleo.org/africae/?do=_checklist_view&document=2652 idem paragraphe 18
- https://books-devel.labocleo.org/africae/?do=_checklist_view&document=2654 & http://checklist.labocleo.org/test/?do=_checklist_view&document=1286 : paragraphe 25 légende d'illustration seule

Il faudrait aussi modifier les titres : 
fr: "Métadonnées d’illustration sans illustration",
en: "Illustration metadata without any illustration"

Et les descriptions : 
```
fr: "<p>Une ou des métadonnées d’illustrations ne sont pas attachées, comme attendu, à une illustration, un tableau ou un média embarqué. L’ordre recommandé pour les métadonnées portant sur les illustrations, tableau et média embarqué est le suivant&nbsp;: titre, illustration, légende, crédits. Il est important de respecter cet ordre pour la bonne génération de la table des illustrations et pour des raisons d’accessibilité.</p><p>Voir <a href=\"https://objs-fr.hypotheses.org/638\">Traitement des images</a></p>",
en: "<p>One or several illustration's metadata aren’t attached to an illustration, table or embedded media, as should be expected. The recommended order for illustration metadata is: title, illustration, caption, credits. It is important to respect this order for the proper generation of the table of illustrations and for accessibility reasons.</p>"
```

**Comment by brrd** [comment]
Je renomme ce test metasillustration:quality(position).

Il me reste encore à tester la modif sur OEB.

**Comment by brrd** [comment]
C'est OK sur OEB.
