### ISSUE TITLE
Doublons mots clés non repérés

### ISSUE THREAD

**Issue by amandine-texier** [OpenEdition/checklist-lodel#12]
Le test index:quality(duplicates) ne repère pas le doublon singulier / pluriel ("development" et "developments") sur ce document : http://checklist.labocleo.org/test/?do=_checklist_view&document=670

**Comment by brrd** [comment]
Ce n'était pas prévu car pas précisé. Mais je peux l'ajouter.

**Comment by amandine-texier** [comment]
Oui volontiers

**Comment by brrd** [comment]
C'est corrigé, comme on peut le voir ici avec le doublon  development/developments : http://checklist.labocleo.org/test/?do=_checklist_view&document=56

En revanche @amandine-texier cela ne fonctionne pas sur l'article que tu cites car cette règle ne s'exécute actuellement que sur les templates index et non sur les articles. Pour l'ajouter sur les articles il faudrait voir ça dans un nouveau ticket.

**Comment by amandine-texier** [comment]
Superbe merci, j'ai fait un nouveau ticket pour le template article,  #59
