### ISSUE TITLE
Nouvelle règle : styles inconnus dans annexes et bibliographie

### ISSUE THREAD

**Issue by amandine-texier** [OpenEdition/checklist-lodel#13]
Ajout d'une nouvelle règle similaire à texte:quality(unknown-styles) : 
- Titre : Styles inconnus utilisés
- Description : Des styles dans votre document source n'ont pas été reconnus. Certains éléments n'ont peut-être pas été interprétés correctement par Lodel. Merci de reprendre votre fichier source et d'appliquer les styles adéquats.
- Condition : classe textes
- Type : warning
- Objet : tester les annexes et bibliographies (dans le back ?) où seuls les styles suivant doivent être utilisés
> p.annexe, p.bibliographie, p.creditillustration, p.crditsillustration, p.citation, p.citationbis, p.citationter, p.titreillustration, p.legendeillustration

Document test valide : http://checklist.labocleo.org/test/?do=_checklist_view&document=341

**Comment by brrd** [comment]
Plutôt que créer une règle qui ferait doublon j'ai ajouté ces cas de figure dans le test existant. Par contre je n'arrive pas à trouver de document avec des styles inconnus pour tester ça. @amandine-texier pourrais-tu m'en indiquer un ?

**Comment by amandine-texier** [comment]
En fait, la plupart des styles qui ne sont pas corrects pour la biblio et l'annexe remontent dans le front j'ai l'impression : http://checklist.labocleo.org/test/?do=_checklist_view&document=866
Mais tout est bien repéré, dont "Paragraphe sans retrait" dans l'annexe

Dis moi si tu as besoin de plus d'exemples, autrement ça me semble bon
