### ISSUE TITLE
Nouvelle règle : styles inconnus dans les notes

### ISSUE THREAD

**Issue by amandine-texier** [OpenEdition/checklist-lodel#14]
Ajout d'une nouvelle règle similaire à texte:quality(unknown-styles) :

- Titre : Styles inconnus utilisés
- Description : Des styles dans votre document source n'ont pas été reconnus. Certains éléments n'ont peut-être pas été interprétés correctement par Lodel. Merci de reprendre votre fichier source et d'appliquer les styles adéquats.
- Condition : classe textes
- Type : warning
- Objet : tester les notes de bas de page et notes de fin où seuls les styles suivant doivent être utilisés
> p.creditillustration, p.crditsillustration, p.citation, p.citationbis, p.citationter, p.titreillustration, p.legendeillustration, p.notesbaspage, p.notefin

**Comment by amandine-texier** [comment]
Document test valide : http://checklist.labocleo.org/test/index.php?id=677

**Comment by brrd** [comment]
Voir #14/

**Comment by amandine-texier** [comment]
Ces notes de fin sont signalées comme problématiques alors que le style fait partie des styles acceptés : http://checklist.labocleo.org/test/?do=_checklist_view&document=175
Mais autrement tous les styles inconnus sont bien signalés !
