### ISSUE TITLE
Modification terminologie template publication

### ISSUE THREAD

**Issue by amandine-texier** [OpenEdition/checklist-lodel#15]
La terminologie utilisée dans Checklist au niveau du template publication fait souvent référence à un "Document" alors qu'il s'agit plutôt d'un "Numéro", serait-il possible de faire les modifications suivantes seulement sur la visualisation d'une publication ?
- dans la barre latérale de Checklist le titre du menu déroulant est "Document" → "Numéro" (et pas "Publication" pour ne pas qu'il y ait confusion avec le bouton "Publier") ;
- dans la barre latérale de Checklist quand la vérification n'a pas encore été faite la légende affiche "Ce document n'a pas encore été vérifié." → "Cette publication n'a pas encore été vérifiée." ;
- dans la table des matières, au niveau du numéro (cf. capture) le titre du menu déroulant est "Document" → "Numéro".
![document-numero](https://user-images.githubusercontent.com/49485044/58461344-b87a9c80-812f-11e9-9d36-0dd489a21b6a.jpg)

**Comment by brrd** [comment]
Voir aussi #53.

**Comment by brrd** [comment]
Conformément à ce qui a été décidé dans #53, les menu sont maintenant tous nommés "Options". Quant à la légende, je pense qu'il y a une erreur de raisonnement. L'icône "?" ne désigne pas la publication mais bien les documents qu'elle contient.

Voici la barre de progression lorsque rien n'est vérifié :

![image](https://user-images.githubusercontent.com/7335302/106483990-716dae80-64af-11eb-9ee2-adfe13e4375a.png)

Ce qui signifie que 4 documents de la publication ne sont pas vérifiés. 

Et voici la même chose avec cette fois-ci un document vérifié :

![image](https://user-images.githubusercontent.com/7335302/106484121-96622180-64af-11eb-99b8-76e53a0528c7.png)

Pourrait-on en rediscuter @amandine-texier car je ne suis pas bien sûr de ce qu'il faut faire ici ?
