### ISSUE TITLE
Afficher "1" quand une seule erreur

### ISSUE THREAD

**Issue by amandine-texier** [OpenEdition/checklist-lodel#16]
Pour les erreurs repérées par les tests qui peuvent être "comptées" (exemple : "Styles inconnus utilisés" ou "Composition des index" mais pas "Erreur de pagination" ou "Absence de la date de publication papier") le nombre d'erreurs s'affiche dans le panneau latéral de Checklist s'il est supérieur à "1", serait-il possible d'afficher également "1" quand une seule erreur est présente pour harmoniser ?

Exemple : http://checklist.labocleo.org/test/?do=_checklist_view&document=342
- 1 Mauvais style de citation
- 1 Styles inconnus utilisés
- 2 Composition des index
- Erreur de pagination
- 3 Absence de nom d'auteur dans une entrée bibliographique

Pas d'urgence.

**Comment by brrd** [comment]
@amandine-texier Je n'y avais pas pensé tout de suite, mais dans la logique interne de Checklist il n'y a pas de distinction entre les erreurs "comptés" et les autres : toutes les erreurs sont dénombrables. Cela veut dire que si j'ajoute le "1", alors toutes les notifications afficheront "1" (ou un autre nombre si plusieurs erreurs).

Dans ton exemple, cela veut dire qu'on aura également : "1 Erreur de pagination". Est-ce que ça irait ?

Sinon il faudra réécrire cette partie du noyau pour ajouter une distinction qui indique si les erreurs affichent un compteur ou non.

**Comment by brrd** [comment]
Précision par rapport à mon message précédent, pour bien expliquer la logique : dans l'idée quand Checklist s'exécute, il compte les occurrences de chacune des erreurs. Si le nombre d’occurrences est zéro alors l'erreur n'est pas affichée. Par conséquent toutes les erreurs affichées ont un compteur supérieur ou égal à 1.

**Comment by amandine-texier** [comment]
Désolée du temps de réponse - du coup je me demande si ça vaut le coup de rajouter "1" devant toutes les erreurs ou si on peut laisser ainsi (je pense pas que ça vaille la peine de modifier le fonctionnement du noyau pour pouvoir distinguer entre les erreurs "comptables" ou non). Je vois avec l'équipe et je réponds ici dès qu'on a décidé !

**Comment by brrd** [comment]
Entre temps j'ai remis le nez dans le code et je pense que, bien que ce soit une modif du core, il ne serait pas trop compliqué de n'afficher le "1" que sur une liste bien précise de tests. Il faudrait juste ajouter un attribut booléen `countable` aux règles pour indiquer si l'on doit forcer l'affichage du compteur. Donc je peux le faire.

Pourrais-tu m'envoyer la liste des erreurs concernées stp @amandine-texier ?

**Comment by amandine-texier** [comment]
Super nouvelle, voici la liste des ID des erreurs concernées :
title:quality(br)
images:existence
title:quality(href)
headings:quality(br)
texte:quality(paragraph-lowercase)
texte:quality(quote-style)
texte:quality(list-style)
title:quality(ponctuation)
texte:quality(champs)
index:quality(format)
index:quality(duplicates)
author:quality
links:quality
note:quality(point)
souspartie:quality

**Comment by brrd** [comment]
C'est corrigé et à jour sur la VM.
