### ISSUE TITLE
Nouvelle règle : absence d'auteur

### ISSUE THREAD

**Issue by amandine-texier** [OpenEdition/checklist-lodel#17]
Ajout d'une nouvelle règle :

- Titre : Absence d'auteur
- Description : Aucun auteur, éditeur scientifique ou collaborateur n'a été indiqué pour ce document.
- Condition : classe textes
- Type : info
- Objet : afficher si les trois champs "auteur", "collaborateur" et "editeurscientifique" sont vides

**Comment by brrd** [comment]
C'est ajouté : http://checklist.labocleo.org/test/?do=_checklist_view&document=842
