### ISSUE TITLE
Donnée supplémentaire à afficher : format fichier importé

### ISSUE THREAD

**Issue by amandine-texier** [OpenEdition/checklist-lodel#18]
Est-il possible de repérer le format du fichier importé (XML, DOC, ODT...) ?

Si c'est le cas, ce serait un vrai bonus de l'ajouter comme métadonnée dans le "cartouche" grisé au niveau des documents, en première position (avant "Date de la publication électronique") avec pour titre "Format du fichier importé" suivi dudit format.

**Comment by brrd** [comment]
Je ne sais pas. Pourrais-tu me fournir plusieurs cas de figure différents (idéalement importées dans un numéro à part) ? Comme ça je pourrai regarder s'il y a une façon de repérer ça.

**Comment by amandine-texier** [comment]
Oui, voici plusieurs cas de figure :
- Numéro entier importé en ZIP avec du XML : http://checklist.labocleo.org/test/index.php?id=696
- Article importé en DOC : http://checklist.labocleo.org/test/index.php?id=680
- Article importé en ODT : http://checklist.labocleo.org/test/index.php?id=694
- Article importé en XML : http://checklist.labocleo.org/test/index.php?id=771

**Comment by amandine-texier** [comment]
Le DOCX est un format accepté maintenant, donc voici un exemple : http://checklist.labocleo.org/test/index.php?id=812

**Comment by brrd** [comment]
> Le DOCX est un format accepté maintenant

@amandine-texier super, tu réponds à ma question sur https://github.com/OpenEdition/OTX/issues/9
Merci !

**Comment by brrd** [comment]
C'est ajouté : http://checklist.labocleo.org/test/?do=_checklist_view&document=698
