### ISSUE TITLE
Mise en cohérence marqueurs et surlignement

### ISSUE THREAD

**Issue by amandine-texier** [OpenEdition/checklist-lodel#21]
Les marqueurs et le surlignement des erreurs n'ont pas été pensés de façon globale dans la demande de création des règles, aussi des ajustements permettraient plus de cohérence.

Serait-il possible d'ajouter des surlignements pour les règles suivantes ?
- [x] title:quality(br) : surligner le contenu du champ concerné (titre ou sous-titre), ex. : http://checklist.labocleo.org/test/?page=checklist&document=152] ;
- [x] headings:quality(br) : surligner le contenu du champ concerné (intertitre, altertitre), ex. : http://checklist.labocleo.org/test/?page=checklist&document=152 ;
- [x] texte:quality(quote-style) : surligner le paragraphe en question, ex. http://checklist.labocleo.org/test/?do=_checklist_view&document=137 ;
- [x] texte:quality(paragraph-lowercase) : surligner le paragraphe en question, ex. http://checklist.labocleo.org/test/?do=_checklist_view&document=137 ;
- [x] texte:quality(list-style) : surligner le paragraphe en question, ex. http://checklist.labocleo.org/test/?do=_checklist_view&document=325 ;
- [x] texte:quality(unknown-styles) : surligner le paragraphe en question, ex. http://checklist.labocleo.org/test/?do=_checklist_view&document=95 ;
- [x] title:quality(ponctuation) : surligner le champ ou le paragraphe en question, ex. http://checklist.labocleo.org/test/?do=_checklist_view&document=139 ;
- [x] index:quality(format) : surligner les entrées concernées, à la fois sur le template article (ex. http://checklist.labocleo.org/test/?do=_checklist_view&document=139) et au niveau des index (ex. http://checklist.labocleo.org/test/?do=_checklist_view&document=58) ;
- [x] note:quality(point) : surligner les notes en question, ex. http://checklist.labocleo.org/test/?do=_checklist_view&document=111.

Serait-il possible d'ajouter des marqueurs et surlignements pour les règles suivantes ?
- [x] datepublipapier:existence : ajouter un marqueur après la date vide ("0000-00-00") et surligner ladite date, ex. : http://checklist.labocleo.org/test/?page=checklist&document=75 (pour la classe textes) ;
- [x] title:existence : surligner et ajouter un marqueur après "Document sans titre", ex. : http://checklist.labocleo.org/test/?page=checklist&document=79 ;
- [x] pagination:quality : surligner la pagination problématique et ajouter un marqueur après cette dernière, ex. http://checklist.labocleo.org/test/?do=_checklist_view&document=139.

**Comment by brrd** [comment]
J'ai corrigé l'ensemble sans soucis, à part pour la dernière demande qui fait apparaître un nouveau bug dans checklist : #56.
