### ISSUE TITLE
Métadonnées dans un accordéon

### ISSUE THREAD

**Issue by brrd** [OpenEdition/checklist-lodel#26]
Afin de simplifier l'affichage des templates et éviter trop de scroll pour des infos secondaires, il est possible de contenir les métadonnées dans un accordéon qui serait replié par défaut sur le template publication et article.

**Comment by amandine-texier** [comment]
Les métadonnées nous semblent avoir un rôle primordial et nous invitons les équipes éditoriales à les vérifier, on préfère qu'elles ne soit pas repliées mais merci pour la proposition.
