### ISSUE TITLE
Un template pour tous les numéros

### ISSUE THREAD

**Issue by brrd** [OpenEdition/checklist-lodel#27]
On peut envisager d'ajouter un template avec la liste des numéros, ce qui faciliterait la navigation. Ou un menu dépliant quelque part dans le template, avec la liste des numéros.

**Comment by brrd** [comment]
Réunion checklist juillet 2019 : 

> Navigation
> Actuellement elle n’est pas très instinctive puisque l’onglet “Checklist” apparaît seulement
sur les pages “publications”, “documents” et “index”, et le fil d’Ariane ne permet pas de
remonter au niveau de tous les numéros, ce qui coupe la navigation.
> Faire en sorte qu’il soit toujours activé, avec un template qui liste toutes les publications
d’un site mais peut-être plus léger que le template publication : la liste des numéros et
seulement le smiley si déjà vérifié ou une icône qui renvoie sur Checklist sur ce numéro -
sans avoir le détail des vérifications.

**Comment by amandine-texier** [comment]
Cela rejoint l'idée évoquée récemment de créer une "home" de Checklist qui répertorierait toutes les pages qui peuvent être testées (numéros / livres, index dans les différentes langues), ça me semble être une excellente idée.

**Comment by brrd** [comment]
Mémo : quand cette page sera écrite, afficher l'onglet Checklist dans le desk Lodel quelque soit le contexte. Lorsque le document n'est pas trouvé dans le contexte, cet onglet lie vers la page "Tous les numéros".

**Comment by brrd** [comment]
Je m'aperçois en travaillant sur un tout autre ticket que Checklist accepte déjà d'être exécuté sur la collection "numéros", et affiche dans ce cas les numéros comme des sous-parties : http://checklist.labocleo.org/test/lodel/edition/?do=_checklist_view&document=73

C'est un gros coup de bol qui n'a rien de volontaire, mais c'est amusant. Et ça sera peut-être utile aux équipes des revues (qui peuvent du coup l'utiliser sans attendre) en attendant qu'on développe quelque chose de plus lisible pour la mise à jour à venir.

**Comment by brrd** [comment]
Et voici : http://checklist.labocleo.org/test/?do=_checklist_view
