### ISSUE TITLE
Ajout d'un bouton pour boucler sur tous les marqueurs

### ISSUE THREAD

**Issue by brrd** [OpenEdition/checklist-lodel#28]
Actuellement pour chaque notification un bouton permet de localiser les marqueurs associés à la notification. On peut envisager un bouton général qui permette de boucler sur tous les marqueurs de la page, toutes notifications confondues.
(Il me semble que screlo propose un tel bouton.)

**Comment by amandine-texier** [comment]
C'est une excellente proposition et il nous semble pertinent de faire ce développement à un moment donné, même si ce n'est pas prioritaire
