### ISSUE TITLE
Déplacement du bouton "Démarrer la vérification"

### ISSUE THREAD

**Issue by brrd** [OpenEdition/checklist-lodel#29]
Pour éviter un surespacement vertical, on peut envisager de déplacer le bouton "Démarrer la vérification" à l'endroit où l'icône s'affiche à la fin de la vérification + le rendre plus visible avec une couleur de fond + rogner un peu de marge verticale.

![image](https://user-images.githubusercontent.com/7335302/59353609-a8fc7580-8d23-11e9-904d-43fb4e34c5f7.png)

**Comment by amandine-texier** [comment]
Un grand oui pour cette proposition qui permettra de mieux distinguer les numéros (et leurs alertes) des unités éditoriales.
