### ISSUE TITLE
Erreur 500 liés à checklist dans les templates appelés en ajax pour les utilisateurs logués

### ISSUE THREAD

**Issue by jfriviere** [OpenEdition/checklist-lodel#32]
Dans les maquettes de revues, on appelle des urls en ajax 
Exemple ici https://journals.openedition.org/caliban/972 : appels ajax :

- https://journals.openedition.org/caliban/972?format=bibliographie&lang=fr&norecordurl=1&annotated=1
- https://journals.openedition.org/caliban/972?format=citedby&lang=fr&norecordurl=1
- https://journals.openedition.org/caliban/972?format=pdfepub&norecordurl=1

Lorsqu'on consulte un site sans être logué dans Lodel, pas de problème. 

Lorsqu'on consulte un site en étant logue dans Lodel, on obtient des erreurs 500 sur ces 3 urls.
Erreur : 
~~~
PHP Error  in file '/data/git/checklist/checklist.php' on line 47 : 
Call to a member function appendChild() on null
~~~

Ca correspond à l'insersion de l'onglet checklist dans le desk Lodel.
Or, les templates des urls appelées en ajax n'incluent pas le desk Lodel, d'où l'erreur php.

Il faut par exemple tester la variable `$ul` avant de faire le appendChild.
https://github.com/OpenEdition/checklist-lodel/blob/master/checklist.php#L45

ou autre chose pour éviter l'inclusion de checklist dans cette situation.

Merci
Jeff

**Comment by brrd** [comment]
Corrigé dans d8fc35a752e06c5a8722364acb29110f2adc9e3a 
Je ne ferme pas le ticket car je n'ai pas la possibilité de tester si ça fonctionne de mon côté.

**Comment by jfriviere** [comment]
J'ai testé sur un espace de dev, c'est bon, merci.
J'attends la mise à jour en prod pour tester et fermer le ticket.
Jeff

**Comment by jfriviere** [comment]
C'est bon pour ce ticket en prod. 
Merci
