### ISSUE TITLE
"images:existence" : faux positifs depuis la table des matières

### ISSUE THREAD

**Issue by amandine-texier** [OpenEdition/checklist-lodel#36]
La règle "images:existence" provoque des faux positifs de façon assez récurrente, notamment lors du contrôle du numéro en repérant des problèmes d'images, mais une fois dans le document (éventuellement après avoir vidé le cache), aucun problème ne se présente.
Exemple : https://edt-journals.openedition.org/equipe-revues/?do=_checklist_view&document=3635, sur les documents https://edt-journals.openedition.org/equipe-revues/?do=_checklist_view&document=3674 et https://edt-journals.openedition.org/equipe-revues/?do=_checklist_view&document=4197

**Comment by brrd** [comment]
@amandine-texier Je n'ai pas accès à ces urls. Pourrais-tu m'ouvrir un compte ou charger ces docs sur la VM stp ?

**Comment by brrd** [comment]
En effet, ça vient de cette ligne qui teste l'affichage de l'image :

https://github.com/OpenEdition/checklist-lodel/blob/6cae591171701cdbc17c31ef7f761f1186ff9492/public/js/checklist-config.js#L284

Vu que l'image n'est pas affichée quand on est sur la toc, checklist revoie une erreur. Je vais chercher un workaround.

**Comment by brrd** [comment]
Le problème des images non chargées se pose quand une image inexistante est appelée plusieurs fois dans le texte. `[Image non convertie]` est affichée la première fois, suivie des appels de l'image inexistante pour chaque occurrence suivante :

* http://checklist.labocleo.org/test/index.php?id=322

Le même article avec une image existante appelée plusieurs fois : 

* http://checklist.labocleo.org/test/index.php?id=801

Workarounds possibles :

* Différencier le test depuis la toc : ne tester que la chaîne `[Image non convertie]` et ne pas montrer de compteur d'erreurs. Le détail des erreurs est visibles quand on se rend sur l'article. C'est sans doute la solution qui nécessite le moins de travail.
* Tester en php avec `file_exists()` (https://www.php.net/manual/fr/function.file-exists.php) et afficher le nombre d'erreurs dans un champ caché du template, qui sera récupéré lors de l'exécution depuis la toc.
* Tester le statuscode des fichiers image de l'article en js avec des requêtes ajax quand le test est lancé depuis la toc. Mais ça risque d'avoir un impact sur les performances de la vérification du numéro.

**Comment by brrd** [comment]
Je peux essayer la 2e solution qui est à mon avis la meilleure et qui consiste à tester l'existence des images dans les templates avec `file_exists`.

@jfriviere @lnprieto J'ai commencé à faire ceci (commité pour l'instant sur une branche à part) : https://github.com/OpenEdition/checklist-lodel/blob/3d1e2b229066cc09b14fb5b2cd2480c7578bd92a/tpl/macros_checklist_article.html#L288-L294

en utilisant la boucle EXTRAIT_IMAGES de Lodel, qui est documentée ici : https://github.com/OpenEdition/lodel/wiki/Lodelscript#la-boucle-extrait_images

Malheureusement j'obtiens une erreur comme quoi cette boucle n'existe pas. Aurait-elle été retirée de Lodel ?

Sinon je peux utiliser un filtre comme celui que nous utilisons chez edinum pour créer la table des illustrations : https://github.com/edinum/lodel-textfunc/blob/master/illustrations.php
Toutefois il semble que le vôtre n'est pas nommé `illustrations` comme le nôtre. Comment s'appelle-t-il ? Comment fonctionne-t-il ?

Si c'est trop compliqué  on utilisera la première méthode (voir mon commentaire plus haut), plus approximative mais qui devrait fonctionner (en tout cas sur les cas que l'on a relevés avec @amandine-texier).

**Comment by brrd** [comment]
J'ai trouvé une méthode simple qui fonctionne avec des expressions régulières : https://github.com/OpenEdition/checklist-lodel/blob/fde9c521aff7ea4b3472ff7f86449ead51a4e59e/tpl/macros_checklist_article.html#L296-L304

Mais après coup à la réflexion je me dis que vous n'avez peut-être pas envie d'envoyer dans `file_exists()` une chaîne qui provient de l'utilisateur, surtout testée en regex comme ceci... 

J'attends vos avis sur ces questions. Encore une fois si c'est trop compliqué on devrait pouvoir bricoler une solution moins complexe (et un peu moins précise/fiable).

**Comment by lnprieto** [comment]
cette dernière stratégie me semble acceptable puisque l'url est bien bornée

**Comment by brrd** [comment]
@lnprieto merci, je vais essayer comme ça alors.

**Comment by brrd** [comment]
J'ai donc utilisé la fonction suivante : https://github.com/OpenEdition/checklist-lodel/blob/e99ee0e2e573e68f93068b8e33bcbc4d337911e7/tpl/macros_checklist_article.html#L299-L307

Voir un exemple de cette fonctionnalité corrigée ici : http://checklist.labocleo.org/test/?do=_checklist_view&document=802
