### ISSUE TITLE
Ajout dans le template article : styles paragraphe notes de fin

### ISSUE THREAD

**Issue by amandine-texier** [OpenEdition/checklist-lodel#37]
Dans le template article de Checklist, tous les styles de paragraphes s'affichent afin qu'on puisse voir comment les paragraphes sont stylés, mais ce n'est pas le cas pour les notes de fin. Exemple : https://edt-journals.openedition.org/equipe-revues/?do=_checklist_view&document=4200

**Comment by brrd** [comment]
OK. Il faut ajouter la classe .ckl-field-text à l'élément data-field="notefin".

**Comment by brrd** [comment]
Corrigé : http://checklist.labocleo.org/test/?do=_checklist_view&document=803
