### ISSUE TITLE
Incohérence num° notes : sauts de paragraphe déclenchent règle

### ISSUE THREAD

**Issue by amandine-texier** [OpenEdition/checklist-lodel#38]
Il semblerait que si des sauts de paragraphe sont présents dans les notes (qu'ils soient justifiés ou non), la règle "texte:quality(notes-numbering)" se déclenche même si la numérotation des notes est par ailleurs cohérente. 

Exemple : https://edt-journals.openedition.org/equipe-revues/?do=_checklist_view&document=4200

**Comment by brrd** [comment]
@amandine-texier C'est bizarre, il y a une citation dans les notes que tu cites. C'est autorisé ça dans Lodel ?

**Comment by amandine-texier** [comment]
Oui c'est autorisé, tout n'est pas encore bien traité dans la maquette mais ce sera bientôt le cas et la prochaine version du schéma TEI le traite correctement. Ça vaut pour les citations, les images, les listes à puces et les tableaux (ces derniers sont traités correctement qu'en DOCX et XML pour l'instant).

**Comment by jfriviere** [comment]
Et oui, c'est ça, même si c'est pas très satisfaisant comme structure html.
Ce qui marque le début de la note c'est l'élement enfant du paragraphe. `a class="FootnoteSymbol"`
Donc en Xpath quelque chose comme ça :

**Comment by brrd** [comment]
Ok merci, je vais corriger ça.

**Comment by brrd** [comment]
Corrigé sur la VM : http://checklist.labocleo.org/test/?do=_checklist_view&document=803
