### ISSUE TITLE
"imageaccroche:existence" : test échoue et donne un message anglais

### ISSUE THREAD

**Issue by amandine-texier** [OpenEdition/checklist-lodel#39]
Si deux couvertures ou deux images d'accroche sont chargées sur un numéro, le test "Pas de couverture" échoue. Ce n'est pas un problème en soi puisqu'au survol du test, un message apparaît pour en expliciter la raison : "More than 1 cover file was found." 

Est-il possible que ce message s'affiche, non pas seulement au survol, mais à la suite du nom du test ayant échoué ? Et en français ?
Exemple : "Pas de couverture : Plus d'un fichier de couverture a été trouvé."

Exemple : https://edt-journals.openedition.org/equipe-revues/?do=_checklist_view&document=3635

**Comment by brrd** [comment]
No problem, je vais faire ça.

**Comment by brrd** [comment]
J'ai ajouté un nouveau test imageaccroche:duplicate pour tester ce cas de figure.
