### ISSUE TITLE
Télécharger la source : problème de formats

### ISSUE THREAD

**Issue by amandine-texier** [OpenEdition/checklist-lodel#4]
La fonction "Télécharger la source au format .doc / Télécharger la source au format XML TEI" présente quelques erreurs :
- http://checklist.labocleo.org/test/?do=_checklist_view&document=152 : le DOC est récupéré qu'on clique sur ".doc" ou "XML-TEI" ;
- http://checklist.labocleo.org/test/?do=_checklist_view&document=322 : "Fichier introuvable" pour les deux formats, la source TEI est pourtant bien téléchargeable dans le formulaire d'édition.

**Comment by brrd** [comment]
En effet, il y a un souci les 2 URL sont identiques. Il faut corriger l'URL de la TEI.

**Comment by brrd** [comment]
J'ai corrigé l'URL de récupération de la TEI : http://checklist.labocleo.org/test/?do=_checklist_view&document=152

En revanche on obtint toujours une erreur quand on demande la source DOC de cet article : http://checklist.labocleo.org/test/?do=_checklist_view&document=322

En fait les liens utilisés sont les mêmes que dans le formulaire d'édition, c'est la raison pour laquelle le comportement est identique.

**Comment by amandine-texier** [comment]
Est-ce que l'erreur sur http://checklist.labocleo.org/test/?do=_checklist_view&document=322 peut venir du fait qu'il n'y ait pas de source DOC, puisqu'il s'agit de XML-TEI ? Est-ce que le problème risque de se poser si on a des sources ODT ou DOCX également ? 

Du coup est-ce qu'il ne serait pas possible de coller au formulaire avec "Récupérer le fichier source" (peu importe son format) ?

**Comment by brrd** [comment]
OK, je viens de voir que le formulaire d'édition de Lodel changeait les liens en fonction de la source. Quand la source est TEI il ne montre que le lien qui pointe sur `type=tei`. Il faut donc adapter les liens au type de source pour éviter cette erreur.

Je viens de trouver la façon de récupérer l'info sur le type de création (tei ou otx) (champ `[#CREATIONMETHOD]` de la table entities). Je vais essayer de personnaliser le menu selon cette donnée si ça te va. 

Si ça te semble utile je peux aussi afficher le type de source dans le template checklist (mais pas obligé).

**Comment by amandine-texier** [comment]
Oui pour la personnalisation du menu pour qu'on récupère le bon fichier source, et pour le type de source ce serait très volontiers, c'était d'ailleurs l'objet de #18

**Comment by brrd** [comment]
C'est corrigé (voir par exemple les liens que tu donnes dans #18).

J'ai changé les dénominations  : le menu "Télécharger la source" n'apparaît pas pour les articles chargés en TEI. Le menu "Télécharger la source (XML)" apparaît partout et renvoie la TEI.

@amandine-texier ça va comme ça ?

NB: curieusement le champ `[#CREATIONMETHOD]` de Lodel renvoie toujours "otx", j'ai donc utilisé `[#CREATIONINFO]` pour récupérer l'extension.

**Comment by amandine-texier** [comment]
Ce fonctionnement me semble parfait mais sur les liens en question, je ne vois nul part "Télécharger la source", seulement l'option "Télécharger la source (XML)"

**Comment by brrd** [comment]
Rahzut ça fonctionnait hier, c'est sans doute d'autres modifications qui ont fait bouger le truc... Je regarde ça.

**Comment by brrd** [comment]
C'est corrigé.

Démos : 

* http://checklist.labocleo.org/test/?do=_checklist_view&document=698
* http://checklist.labocleo.org/test/?do=_checklist_view&document=680
* http://checklist.labocleo.org/test/?do=_checklist_view&document=694
* http://checklist.labocleo.org/test/?do=_checklist_view&document=771
