### ISSUE TITLE
"links:quality" se déclenche sur les fichiers annexes

### ISSUE THREAD

**Issue by amandine-texier** [OpenEdition/checklist-lodel#40]
La règle vérifiant la qualité des liens se déclenche sur les liens des fichiers mis en annexe sur un document. Exemple avec une image d'accroche : https://edt-journals.openedition.org/equipe-revues/?do=_checklist_view&document=4157

Est-il possible que la règle ne teste pas ces liens vers des fichiers annexes, quels qu'ils soient (vu qu'ils apparaissent comme des liens relatifs) ?

**Comment by brrd** [comment]
Corrigé sur la VM : http://checklist.labocleo.org/test/?do=_checklist_view&document=804
