### ISSUE TITLE
Menu déroulant "Document" pas cliquable partout

### ISSUE THREAD

**Issue by amandine-texier** [OpenEdition/checklist-lodel#41]
Le menu déroulant "Document" sur les templates publication et article, n'est pas cliquable au niveau du triangle inversé :
<img width="255" alt="clic-template-publication" src="https://user-images.githubusercontent.com/49485044/66744023-a6e62700-ee7b-11e9-97fe-5700002cf5d0.png">
<img width="632" alt="clic-sommaire" src="https://user-images.githubusercontent.com/49485044/66744021-a64d9080-ee7b-11e9-85b4-3407812b2156.png">
Les clics sur le triangle ne font rien.

**Comment by brrd** [comment]
Corrigé dans https://github.com/OpenEdition/checklist

Voir par exemple : http://checklist.labocleo.org/test/?do=_checklist_view&document=322
