### ISSUE TITLE
Longs liens dépassent du template article

### ISSUE THREAD

**Issue by amandine-texier** [OpenEdition/checklist-lodel#42]
Des liens assez longs dépassent du template article et déforment celui-ci, le rendant moins facilement utilisable (nécessaire d'aller chercher les boutons de navigation avec la barre de défilement par exemple).

Voir https://edt-journals.openedition.org/equipe-revues/?do=_checklist_view&document=4241 (notes 3 et 4) et https://edt-journals.openedition.org/equipe-revues/?do=_checklist_view&document=4218 (notes 3 et 4)

**Comment by brrd** [comment]
Voici : http://checklist.labocleo.org/test/?do=_checklist_view&document=842

Il reste une barre de défilement horizontale mais je peux difficilement faire mieux. Il existe une méthode plus complexe avec du JS qu'on pourra mettre en place si vous constatez encore des problèmes.

**Comment by amandine-texier** [comment]
Sur mes écrans en tous cas, le problème est tout à fait résolu et sans barre de défilement horizontale, merci !
