### ISSUE TITLE
Ajouter le statut de publication dans le template

### ISSUE THREAD

**Issue by amandine-texier** [OpenEdition/checklist-lodel#44]
Actuellement les statuts de publication des textes et publications (brouillon, prêt à publier, publié, protégé) ne sont pas affichés dans Checklist, il faudrait ajouter l’information dans le cartouche, en tout premier, précédé de “Statut de publication”.

**Comment by brrd** [comment]
Voir https://github.com/OpenEdition/lodel/blob/7573530a49ed81263ee43cd71a7c25bba0a7add4/share/macros/macros_interface.html#L1376
