### ISSUE TITLE
Validation filtre, rajout bouton “OK”

### ISSUE THREAD

**Issue by amandine-texier** [OpenEdition/checklist-lodel#46]
L’utilisation du filtre “papier” n’est pas très instinctive, comme il n’y a pas de validation, il est difficile de savoir si le fait de cocher ou décocher la case a été pris en compte. La tentation est de cliquer sur “Vider le cache” ce qui pose problème.
Serait-il possible de rajouter un bouton “OK” à côté ou en dessous du filtre pour valider la modification et fermer le volet de gauche ?

**Comment by brrd** [comment]
C'est fait.
