### ISSUE TITLE
Pouvoir activer Checklist en backoffice

### ISSUE THREAD

**Issue by amandine-texier** [OpenEdition/checklist-lodel#47]
Actuellement l’onglet “Checklist” n’apparaît que dans le front, au niveau des pages index, textes et publications. Serait-il possible d’afficher l’onglet “Checklist” également dans le backoffice, notamment au niveau des publications ?
Par exemple, ici : https://edt-journals.openedition.org/equipe-revues/lodel/edition/index.php?id=3635

**Comment by brrd** [comment]
C'est sans doute possible, reste à savoir comment... et il faut s'y plonger pour le savoir.

**Comment by brrd** [comment]
C'est fait. Ça fonctionne dans trois contextes : 

* vue Edition, quand un `id` (sauf 0) est présent dans l'URL
* formulaire d'édition d'une entité
* onglet Index

Actuellement cela risque de mener à des affichages incohérents pour tous les types non supportés par Checklist (exemple : sous-partie, billet, etc.). Je vais ouvrir un nouveau ticket pour que l'on gère correctement tout ça.
