### ISSUE TITLE
Ajouter les crédits de l’outil et un lien vers Github

### ISSUE THREAD

**Issue by amandine-texier** [OpenEdition/checklist-lodel#48]
Il faudrait rajouter les crédits de développement de Checklist ainsi qu’un lien qui renvoie vers Github pour les utilisateurs curieux qui souhaiteraient en savoir plus. Dans le volet “Préférences” par exemple ?

**Comment by brrd** [comment]
C'est fait. @amandine-texier je te laisse me dire si le message est ok ou s'il faut le changer.

**Comment by amandine-texier** [comment]
Je chipote mais est-ce qu'il ne serait pas mieux de remplacer le symbole de copyright par celui de copyleft 🄯 ? Et une espace entre "Brouard / OpenEdition" pour que ça fasse moins bloc ?
Autrement ça me semble parfait !

**Comment by brrd** [comment]
J'adore le chipotage sur la typo ! 😀 

Bien vu pour le copyleft !

En revanche, objection votre honneur concernant les espaces autour du slash. Il n'y a rien dans le code typo à ce sujet vu que le slash n'est pas historiquement utilisé dans la typographie française, mais on peut regarder le Chicago Manual of Style :

> If the slash divides two words, there is no space. If it divides two phrases or sentences (or a single word from a phrase), it requires a space before and after. 

https://www.chicagomanualofstyle.org/qanda/data/faq/topics/Punctuation/faq0096.html

Dis-moi ce que tu en penses et je ferai comme tu veux !

**Comment by brrd** [comment]
Bon après à la réflexion c'est vrai qu'on peut considérer que "Thomas Brouard" est une "phrase" (= expression) puisque deux mots... bref, dis-moi.

**Comment by amandine-texier** [comment]
Bien vu pour les espaces et le slash, même MLA et APA sont d'accord !
C'est pas très clair pour moi non plus si ce qui est une expression et ce qui ne l'est pas donc on peut laisser comme ça... Ou sinon on peut mettre "Thomas Brouard et OpenEdition" ? 😀 

Mais c'est peut-être plus commun d'utiliser un slash dans ce cas, donc je te laisse trancher !
