### ISSUE TITLE
Ajouter des métadonnées dans le template “article”

### ISSUE THREAD

**Issue by amandine-texier** [OpenEdition/checklist-lodel#52]
Des métadonnées sont manquantes dans le template article :
- Index funder à rajouter dans la "Section Métadonnées", en dernier après "pagination", afficher les champs fundername et grantnumber séparés par une virgule et précédés de "Financement" (variable en anglais (en) "Funder"). Exemple : https://edt-journals.openedition.org/equipe-revues/3674
Financement fundername, grantnumber
Financement        Fundação para a Ciência e a Tecnologia, Ref. PTDC/ANT/65857/2006
- collaborateur à rajouter dans la "Section Personnes", après "editeurscientifique". Exemple : https://journals.openedition.org/galliap/401 ;
- directeurfouilles à rajouter dans la "Section Personnes" après "collaborateur". Exemple : https://journals.openedition.org/archeomed/7915 ;

**Comment by brrd** [comment]
C'est ajouté. Voici un exemple : http://checklist.labocleo.org/test/?do=_checklist_view&document=95
