### ISSUE TITLE
Modification terminologie template index

### ISSUE THREAD

**Issue by amandine-texier** [OpenEdition/checklist-lodel#53]
Sur les template de pages d'index, il faudrait modifier la terminologie : 

- "Index" à la place de "Document"
- "Cet index est correctement composé / très bien composé / contient des erreurs de composition" à la place de "Ce document..."

![image](https://user-images.githubusercontent.com/49485044/67779124-7fd74a00-fa64-11e9-9491-fd6493fbe229.png)
Exemple : https://edt-journals.openedition.org/equipe-revues/?do=_checklist_view&document=241

**Comment by brrd** [comment]
Cette question rejoint #15.

Vu de loin c'est faisable mais ça va ajouter de la complexité au code car ce n'est pas prévu au départ. Dans les quelques situations qui posent problème, pourrait-on éventuellement trouver une seule formule qui convienne à tous les cas de figure ? Ça simplifierait pas mal les choses.

Sinon il faudra ajouter cette fonctionnalité (= pouvoir modifier les intitulés d'interface selon le contexte) au script.

**Comment by amandine-texier** [comment]
Proposition qu'il faudra valider en interne chez OE : modifier par "Cette page est correctement composée", ce qui convient à la fois pour les numéros, livres, articles, chapitres et index.

Pour le menu déroulant "Options" ? Puisqu'il s'agit d'accéder aux différentes possibilités liées à la page (voir / éditer / parcourir). Tout cela est à reconfirmer mais permettrait de régler le "problème" facilement !

**Comment by brrd** [comment]
Oui, je confirme qu'une solution de ce genre serait beaucoup plus simple à mettre en place.

**Comment by brrd** [comment]
Finalement j'ai pu afficher "Document" ou "Index" selon le contexte. En revanche, le titre des menus est toujours "Options".

![image](https://user-images.githubusercontent.com/7335302/106294116-0e7ddc80-624f-11eb-80ea-bdc8f913a280.png)
