### ISSUE TITLE
Nouvelle règle : caractères non Unicodes

### ISSUE THREAD

**Issue by amandine-texier** [OpenEdition/checklist-lodel#54]
Pour cette nouvelle règle, il faudrait que Checklist teste au niveau “textes” la présence de caractères non Unicode, si c’est le cas, cet avertissement devra apparaître (niveau “danger”).

Nom : Présence de caractères non Unicode
Description : `<p>Ce document contient des polices non Unicode qui ne sont pas compatibles avec un affichage sur le web. Il est nécessaire d’utiliser des polices respectant la norme Unicode dans ce document.</p><p>Voir sur la Maison des Revues et des Livres&nbsp;: <a href=\"http://www.maisondesrevues.org/120\" target=\"_blank\">Des caractères spéciaux sont mal affichés</a></p>`

Exemple : https://edt-journals.openedition.org/equipe-revues/4276

**Comment by brrd** [comment]
Désolé mais sauf erreur de ma part je ne pense pas que ce soit possible. Il n'existe pas de "caractères non-Unicode" (en revanche une police peut respecter Unicode ou non).

Pour expliquer les choses simplement : en informatique tous les caractères sont encodés avec un code unique. Par exemple, le code 0041 correspond à la lettre A dans le standard Unicode.

Dans une police non Unicode (comme Symbols par exemple), le caractère 0041 affichera un autre caractère, comme par exemple une ★ (j'invente). Le problème c'est que "du point de vue informatique" il n'y a aucune différence entre ce caractère ★ affiché dans cette police et un caractère A affiché dans une police Unicode : dans les deux cas c'est encodé 0041. Point. La seule manière de le constater malheureusement, c'est l'œil humain (aujourd'hui, en tout cas).

On peut éventuellement simuler ce genre de test en considérant que seuls les caractères d'une plage précise sont safe (caractères latins par exemple), et que les autres plages sont "suspectes". Car souvent les polices non Unicode vont plutôt utiliser un code "peu utilisé" pour leurs caractères. Par exemple, elles utiliseront le code 0541 (plutôt que 0041) pour afficher le caractère ★. Or en Unicode 0541 correspond normalement au caractère Ձ. 

Du coup, une solution de contournement revient à dire que seuls les caractères entre 0000 et 0240 sont autorisés et que les autres sont considérés comme suspect car moins courants et ainsi potentiellement pas conforme à Unicode. Mais c'est très hasardeux, et si ça fonctionne (à peu près) pour tester des noms d'auteurs, ça risque de faire des faux positifs tout le temps dans du texte qui peut contenir de l'arabe, du chinois, des maths, etc.

C'est aussi un peu cette logique qui est utilisée dans screlo pour tester la présence de caractères Symbols : on énumère tous les caractères qui sont utilisées par la police Symbols (et qui par chance ne sont pas des caractères très utilisés en Unicode) et on considère que quand l'un s'affiche il y a de grande chances que ce soit une trace d'utilisation de la police Symbol :

```

```

Mais ça reste un bricolage très sommaire et spécifique.

Bref, tout ce laïus pour expliquer en quoi c'est très compliqué (voire impossible) de tester ce genre de choses et pourquoi tous les tests qu'on mettra en place pour ça sont des bricolages qui malheureusement ne seront jamais fiables à 100%. On n'échappera pas encore totalement à la relecture par un être humain :-)

**Comment by amandine-texier** [comment]
Merci pour l'explication, je ferme donc le ticket puisqu'il semble dommage de passer du temps de développement sur une règle qui ne pourra fonctionner que plus ou moins et qui semble si complexe !
