### ISSUE TITLE
Afficher l'aide quand on clique sur un marker

### ISSUE THREAD

**Issue by brrd** [OpenEdition/checklist-lodel#58]
Il serait logique d'afficher l'aide dans le panneau latéral quand un marqueur est cliqué dans le texte.

**Comment by brrd** [comment]
J'ai ajouté ça, c'était rapide à faire. À tester.

**Comment by amandine-texier** [comment]
Ça marche très bien ! Testé ici : http://checklist.labocleo.org/test/?do=_checklist_view&document=95
