### ISSUE TITLE
Ajouter la règle index:quality(duplicates) au template article

### ISSUE THREAD

**Issue by amandine-texier** [OpenEdition/checklist-lodel#59]
La règle index:quality(duplicates) fonctionne actuellement sur le template index (http://checklist.labocleo.org/test/?do=_checklist_view&document=56), ce serait bien qu'elle fonctionne également sur le template article.

Exemple : http://checklist.labocleo.org/test/?do=_checklist_view&document=670

**Comment by brrd** [comment]
Cela implique quelques modifications du test car il faut distinguer les différents index lors de la recherche de doublons. Exemple : ne pas considérer que le mot-clé "image" est un doublon du keyword "image".

**Comment by brrd** [comment]
C'est fait : http://checklist.labocleo.org/test/?do=_checklist_view&document=670
