### ISSUE TITLE
Listes mal formatées : non reconnues

### ISSUE THREAD

**Issue by amandine-texier** [OpenEdition/checklist-lodel#6]
Test : texte:quality(list-style)

Certaines listes mal formatées de façon assez "évidente" ne sont pas reconnues par le test : http://checklist.labocleo.org/test/?do=_checklist_view&document=137 §7-9 et §11-14.

**Comment by brrd** [comment]
Pour info sache que tu peux citer directement les paragraphes dans checklist :

http://checklist.labocleo.org/test/?do=_checklist_view&document=137#p7
http://checklist.labocleo.org/test/?do=_checklist_view&document=137#p11
