### ISSUE TITLE
Modification de titre et description de deux règles

### ISSUE THREAD

**Issue by amandine-texier** [OpenEdition/checklist-lodel#60]
Deux textes à modifier : 
- le titre de la règle texte:quality(quote-style), pour rajouter un point d’interrogation : “Mauvais style de citation&nbsp;?”
- la description de la règle pagination:quality pour rappeler qu’il faut que le séparateur soit un tiret - et pas autre chose.
`"La pagination de la version papier n’est pas correctement renseignée, le format attendu est page de début-page de fin, exemple 12-72. Le séparateur doit être un tiret quart de cadratin.</p><p>Voir sur la Maison des Revues et des Livres&nbsp;: <a href=\"http://www.maisondesrevues.org/1295\" target=\"_blank\">Styler les métadonnées de l’article</a></p>"`

**Comment by brrd** [comment]
Corrigé. Voir ici : http://checklist.labocleo.org/test/?do=_checklist_view&document=139
