### ISSUE TITLE
Distinguer visuellement les publications dans la table des matières

### ISSUE THREAD

**Issue by brrd** [OpenEdition/checklist-lodel#62]
...peut-être avec une couleur d'arrière plan légèrement plus foncée ?

**Comment by brrd** [comment]
La publication en cours a maintenant une autre couleur d'arrière plan:

![image](https://user-images.githubusercontent.com/7335302/106162101-01e28100-6188-11eb-98c7-9cf90c5ae1ae.png)

**Comment by brrd** [comment]
À la réflexion, on peut peut-être améliorer cette présentation en utilisant inscrivant les résultats directement à la suite des métadonnées du numéro, sans encadré.

Exemple : 

![image](https://user-images.githubusercontent.com/7335302/107374305-badd7f80-6ae7-11eb-9cf4-ade2029b3647.png)


Par rapport à cette image, on pourrait éventuellement ajouter des titres de sections "Qualité de la publication" et "Qualité des articles" (respectivement avant les tests de la publication et des articles).

Qu'en penses-tu @amandine-texier ?

**Comment by amandine-texier** [comment]
C'est une excellente proposition, si c'est possible ça me semble effectivement plus clair !
Je chipote mais est-ce envisageable que le smiley qui correspond au statut de la publication soit centré, et pas aligné à droite comme pour les UE ?

Des titres de sections "Qualité de la publication / des documents" (plutôt que articles) me semblent tout à fait bienvenues également

**Comment by brrd** [comment]
Ok, je vais retravailler tout ça.

**Comment by brrd** [comment]
J'ai donc revu la présentation générale des tables des matières pour que ce soit plus aéré et plus lisible. Que penses-tu de ces modifications @amandine-texier ?

@amandine-texier

**Comment by brrd** [comment]
Une copie d'écran de cette nouvelle version :

![image](https://user-images.githubusercontent.com/7335302/110343520-dbd4ba00-802c-11eb-99db-b146b09704d4.png)

**Comment by brrd** [comment]
J'ai effectué les deux corrections convenues : nouvelle icône + renommer "Qualité des contenus" en "Qualité des documents".
