### ISSUE TITLE
Numérotation des paragraphes erronée

### ISSUE THREAD

**Issue by amandine-texier** [OpenEdition/checklist-lodel#65]
Les illustrations sont prises en compte dans la numérotation des paragraphes sur le template article, du coup la numérotation ne correspond pas avec la visualisation "Site" du document.

Exemple :  http://checklist.labocleo.org/test/?do=_checklist_view&document=873 & http://checklist.labocleo.org/test/index.php?id=873 le paragraphe 4

**Comment by brrd** [comment]
Hmm... Je pensais que ce serait simple mais ça ne l'est pas en fait. Le problème c'est qu'actuellement les illustrations ne font l'objet d'aucun traitement spécifique, si bien qu'elles sont intégrées dans des paragraphes de texte normaux.

Exemple ici : http://checklist.labocleo.org/test/?do=_checklist_view&document=873

Où on obtient : 

![image](https://user-images.githubusercontent.com/7335302/75760184-22674880-5d37-11ea-992f-6cfa94ce27ea.png)

Il faudrait utiliser un filtre php spécifique pour que les images soit plutôt passées dans un container sans la classe texte. Le soucis c'est qu'il me semble que les filtres que vous utilisez font beaucoup plus que ça, et ajoutent les numéros de paragraphes sous forme de tableau...

**Comment by brrd** [comment]
Bon, en fait je viens de bricoler une solution en JS. À tester en conditions réelles : http://checklist.labocleo.org/test/?do=_checklist_view&document=873
(CTRL+F5 si ça ne s'affiche pas directement)
