### ISSUE TITLE
Incohérence num° notes : chiffres romains problématiques

### ISSUE THREAD

**Issue by amandine-texier** [OpenEdition/checklist-lodel#7]
Quand une liste à puce se suit de manière cohérente en chiffres romains, elle est pourtant signalée comme incohérente par le test texte:quality(notes-numbering), cf. http://checklist.labocleo.org/test/?do=_checklist_view&document=340

**Comment by brrd** [comment]
C'est corrigé : http://checklist.labocleo.org/test/?do=_checklist_view&document=674#ftn27

Par contre je cherche un article démo avec le problème de numérotation incohérente (idéalement en chiffres arabes et romains) pour vérifier que cette correction n'a rien cassé et je n'arrive pas à remettre la main dessus. @amandine-texier est-ce que tu aurais une URL stp ?

**Comment by amandine-texier** [comment]
Voici un exemple de numérotation incohérente : http://checklist.labocleo.org/test/?do=_checklist_view&document=322 (toujours bien relevé par Checklist)

Par contre pour http://checklist.labocleo.org/test/?do=_checklist_view&document=674#ftn27, de mon côté Checklist signale toujours les notes numérotées en chiffres romains alors qu'elles devraient être cohérentes (j'ai vidé le cache mais ça ne change rien...)

**Comment by brrd** [comment]
En effet, il y avait une coquille dans le code. Au passage ça m'a permis de détecter et corriger un autre problème quand les notes sont englobées par un span de lang (merci MS Word).

Normalement tout est bon, @amandine-texier je te laisse fermer le ticket si c'est ok pour toi.

**Comment by amandine-texier** [comment]
Les chiffres romains ne sont plus signalés par contre sur http://checklist.labocleo.org/test/?do=_checklist_view&document=674 les notes 8 à 26 sont signalées incohérentes alors qu'il n'y a pas de raison

**Comment by brrd** [comment]
En effet... C'est corrigé : http://checklist.labocleo.org/test/?do=_checklist_view&document=674
