### ISSUE TITLE
Nouvelle règle pour le type "compterendu"

### ISSUE THREAD

**Issue by amandine-texier** [OpenEdition/checklist-lodel#70]
Quatre métadonnées sont liées au type de la classe textes "compterendu" : 
- noticebibliooeuvre
- titreoeuvre
- datepublicationoeuvre
- auteuroeuvre

Une nouvelle règle pourrait être intéressante : tester que tous ces champs soient remplis pour ce type précis. Type avertissement ?

Exemple : https://edt-journals.openedition.org/equipe-revues/?do=_checklist_view&document=4280 il manque "datepublicationoeuvre"

**Comment by brrd** [comment]
Faut-il obligatoirement que ces quatre métadonnées soient remplies pour tous les comptes rendus (il me semble que certains comptes-rendus n'utilisent aucune des quatre), ou seulement si l'une des quatre au moins existe ? 

Il me semble que ces champs ne sont pas toujours pertinents pour tous les comptes rendus. Par exemple, il n'y a pas d'auteur pour une AG ou un colloque.

Quid des documents du type "notedelecture" ?

**Comment by amandine-texier** [comment]
J'ai vu avec les collègues de Journals : c'est bien une recommandation de remplir les quatre métadonnées (cf. http://www.maisondesrevues.org/942) du coup je confirme qu'il faudrait que la règle soit de type avertissement (et pas danger).

Le type "notedelecture" est visiblement en voie d’extinction et il n'est plus conseillé de l'utiliser donc mieux vaut l'écarter de cette nouvelle règle.

**Comment by brrd** [comment]
@amandine-texier Peux-tu m'indiquer les textes à utiliser stp (titre, description au moins en français) ?

**Comment by amandine-texier** [comment]
Désolée d'avoir tardé, les voici : 

Titre : Métadonnées de l’œuvre commentée incomplètes
Description : Pour les compte-rendus, il est recommandé de renseigner le titre, l’auteur, la notice bibliographique et la date de publication de l’œuvre commentée. Une ou plusieurs de ces métadonnées sont manquantes. Voir sur la _Maison des Revues et des Livres_  : [Stylage des recensions](http://www.maisondesrevues.org/942).

**Comment by brrd** [comment]
Fait : 
* checklist.labocleo.org/test/?do=_checklist_view&document=917
* http://checklist.labocleo.org/test/?do=_checklist_view&document=914
