### ISSUE TITLE
Numéro ouvert

### ISSUE THREAD

**Issue by amandine-texier** [OpenEdition/checklist-lodel#71]
Établir quelles règles doivent être effectués ou pas si numeroouvert est coché dans les champs publication.
Notamment rajouter le champ "historique" dans le template.

Exemple : https://journals.openedition.org/tvseries/1603

**Comment by amandine-texier** [comment]
Effectivement, pour tester les numéros ouverts, il faudrait, si le champ numeroouvert est coché au niveau de la publication : 
- rajouter le champ "historique" (champ multilingue) dans le template publication ;
- désactiver le filtre tag-paper sur ce type ;
- ajouter une règle, cf. #75 ;
- le type affiché (cf. #72) pourrait-il être "Numéro ouvert" ?

**Comment by brrd** [comment]
* [x] rajouter le champ "historique" (champ multilingue) dans le template publication ; => Fait : http://checklist.labocleo.org/test/?do=_checklist_view&document=347&clearcache=oui
* [ ] désactiver le filtre tag-paper sur ce type ;
* [ ] ... et sur les enfants
* [ ] le type affiché (cf. #72) pourrait-il être "Numéro ouvert" ?
* ajouter une règle => voir #75 ;

**Comment by brrd** [comment]
C'est résolu : http://checklist.labocleo.org/test/?do=_checklist_view&document=347&clearcache=oui

Peut-être faudrait-il supprimer le champ "Numéro ouvert" du cartouche qui fait maintenant doublon ?

![image](https://user-images.githubusercontent.com/7335302/107373588-fe83b980-6ae6-11eb-978c-2fcd04a0cdae.png)

**Comment by brrd** [comment]
Je découvre en écrivant #75 le fonctionnement de ce champ que je ne connaissais pas. 

Vu que, d'après les instructions de la règle, la case "Numéro ouvert" doit être décochée quand le numéro est fermé, n'y a-t-il pas un souci de logique par rapport aux modifications demandées dans ce ticket, qui ne fonctionneront plus une fois que la case sera décochée (vu que c'est cette case qui permet de déterminer si le numéro est ouvert).

Autrement dit, quand le numéro sera fermé et la case décochée : 

* le numéro ne sera plus distingué comme "Numéro ouvert"
* l'historique ne sera plus affiché
* les règles "papier" s'appliqueront de nouveau

Pour l'historique on peut décider de l'afficher quand il comprend du texte, indépendamment de la cas "Numéro ouvert". Mais pour le reste il y a peut-être quelque chose à clarifier par rapport à vos données ?

**Comment by amandine-texier** [comment]
Je confirme que du coup le champs "Numéro ouvert" oui / non du cartouche est redondant et qu'on peut le supprimer.

Je me suis renseignée et effectivement, le champ "historique" reste rempli même une fois que la case numeroouvert est décochée, du coup il vaudrait mieux l'afficher quand il comprend du texte comme pour les autres champs (désolée pour la mauvaise indication).

Le reste du comportement est bien ce qui est attendu : une fois que le numéro ouvert est décoché, il devient un numéro comme les autres et ne doit plus être distingué comme numéro ouvert. Du coup la règle ne doit plus s'afficher.
