### ISSUE TITLE
Ajouter type de publications / textes

### ISSUE THREAD

**Issue by amandine-texier** [OpenEdition/checklist-lodel#72]
Actuellement Checklist n'affiche pas dans les templates publications et articles le type de document en question (numero, rubriqueannuelle / article, editorial, compterendu), il faudrait l'afficher quelque part, décider où.

**Comment by brrd** [comment]
J'ai ajouté le type sur les publications et les textes dans le cartouche :

![image](https://user-images.githubusercontent.com/7335302/106778643-7a44b880-6646-11eb-80d3-5e9235184f2e.png)

@amandine-texier est-ce que cela convient ?

**Comment by amandine-texier** [comment]
C'est parfait merci !
