### ISSUE TITLE
Utiliser Checklist dans une autre langue que le FR

### ISSUE THREAD

**Issue by amandine-texier** [OpenEdition/checklist-lodel#73]
Actuellement Checklist ne s'affiche qu'en français, il faudrait paramétrer Checklist pour que la langue de navigation puisse changer d’une langue à l’autre à l’aide de boutons de navigation.

**Comment by brrd** [comment]
Pour pouvoir utilise Checklist dans une autre langue, il faudra traduire :
* les règles : https://github.com/OpenEdition/checklist-lodel/blob/master/public/js/checklist-config.js
* l'interface (du noyau) : https://github.com/OpenEdition/checklist/blob/master/src/ui/locales/fr.json

Pour la partie LodelScript, pour l'instant la quasi totalité des textes est récupérée dans le ME. Il faudra trouver une solution pour les quelques situations où ce n'est pas possible (passer par des variables de traduction à charger dans Lodel me semble un peu lourd pour seulement deux ou trois chaînes).

Il faudrait avoir au moins une autre langue pour tester l'ajout de cette fonctionnalité. Je peux m'occuper de faire une traduction en anglais, sur laquelle vous pourrez revenir après coup si besoin. @amandine-texier qu'en penses-tu ?

**Comment by amandine-texier** [comment]
Si tu as le temps de t'occuper de la traduction en anglais ça me semble parfait et sinon je peux aider.

Effectivement si on peut éviter de passer par des variables de traduction à rajouter dans Lodel ce serait chouette. Ou alors faire appel à celles qui existent déjà, si on peut, quand les textes ne sont pas récupérés dans le ME ? Il faudra d'ailleurs s'assurer que les champs du ME correspondants aient bien des variables en anglais (je ne sais pas pour OEJ mais pour Books, ce n'est pas - encore - le cas pour tous les champs).

**Comment by brrd** [comment]
OK, je vais faire une proposition de traductions en anglais auxquelles vous pourrez apporter les modifications que vous voudrez.

Et les quelques traductions des templates qui ne pourront pas être récupérées dans le ME seront intégrées dans les fichiers de Checklist, ça semble le plus simple en effet.

**Comment by brrd** [comment]
Voici déjà la traduction du core : https://github.com/OpenEdition/checklist/blob/master/src/ui/locales/en.json

**Comment by brrd** [comment]
@amandine-texier Une question concernant tous les liens "Voir sur la Maison des Revues et des Livres" : j'ai l'impression que la documentation n'est pas disponible en anglais. Du coup j'imagine que je supprime ces liens vers la MDR ?

**Comment by amandine-texier** [comment]
Oui je pense que tu peux supprimer ; deux autres sites sont en préparation qui vont remplacer la MDRL, un en français et l'autre en anglais, dès que j'ai plus d'infos je pourrai voir quand il faut qu'on modifie les liens (pour le faire en une seule fois idéalement)

**Comment by brrd** [comment]
Voici les traductions des règles dans ce commit : dd95193f7a95cc0d431f1613d0f830a691ec18c5

Je ne suis pas traducteur, donc il y a sans doute des choses à corriger. N'hésite pas à m'envoyer vos retours (via une pull request si possible).

Il reste encore les traductions dans les templates LodelScript.

**Comment by brrd** [comment]
Je m'aperçois en écrivant cette fonctionnalité qu'il serait logique de reprendre la langue définie dans les paramètres de l'utilisateur dans Lodel, plutôt que créer un nouveau menu dissocié juste pour Checklist (ce que j'ai fait jusqu'à présent). Qu'en penses-tu @amandine-texier ?

**Comment by amandine-texier** [comment]
Effectivement je n'y avais pas pensé non plus ; plutôt que la langue définie sur le compte utilisateur, est-ce qu'on ne peut pas récupérer directement la langue de l'interface, paramétrée au niveau de l'onglet administration (cf. http://checklist.labocleo.org/test/lodel/admin/index.php) ?

**Comment by brrd** [comment]
En fait cette langue est bien celle de l'utilisateur, les deux champs correspondent en réalité au même paramètre. Mais pour des histoires de session les deux ne fonctionnent pas exactement de la même façon (l'un fait basculer immédiatement l'interface dans la nouvelle langue, tandis l'autre n'est effectif qu'après la reconnexion de l'utilisateur).

Je peux éventuellement ajouter un champ de changement de langue dans les options de Checklist pour permettre de modifier cette option sans avoir à passer par le backoffice. Qu'en penses-tu ?

**Comment by brrd** [comment]
> Je peux éventuellement ajouter un champ de changement de langue dans les options de Checklist pour permettre de modifier cette option sans avoir à passer par le backoffice. Qu'en penses-tu ?

En fait ce n'est pas si simple à mettre en place, il y a bien [une fonction pour ça](https://github.com/OpenEdition/lodel/blob/3838219c67d92ca9315e00311071e5404f5579c6/share/js/interface.js#L72) mais je ne suis pas sûr de pouvoir l'utiliser dans le contexte de Checklist. Donc dans un premier temps je vais intégrer sans cette option pour faire simple, et si nécessaire on l'ajoutera dans un second temps.

**Comment by amandine-texier** [comment]
Je ne savais pas qu'il s'agissait du même paramètre affiché à deux endroits différents, tout à fait d'accord pour partir là-dessus et voir plus tard si on veut intégrer l'option à même Checklist.

**Comment by brrd** [comment]
Cette fonctionnalité est écrite et la VM est à jour.

Le changement de langue se fait donc via le panneau d'administration de Lodel. Actuellement deux langues sont gérées : le français (par défaut) et l'anglais.

Les différentes traductions utilisées sont réparties dans plusieurs endroits :

* Ici pour les traductions du noyau : https://github.com/OpenEdition/checklist/blob/master/src/ui/locales/
* Dans le ME pour les noms de champs.
* Dans ce fichiers pour les autres traductions des templates LodelScript : https://github.com/OpenEdition/checklist-lodel/blob/master/tpl/checklist_translations.html
* Et dans la configuration de Checklist pour les traductions des règles/rapports : https://github.com/OpenEdition/checklist-lodel/blob/master/public/js/checklist-config.js
