### ISSUE TITLE
Format nom auteur : maj et mauvais format non reconnus

### ISSUE THREAD

**Issue by amandine-texier** [OpenEdition/checklist-lodel#8]
Le test author:quality(format) semble avoir du mal à : 
- reconnaître un nom d'auteur bien composé en arabe, cf. : http://checklist.labocleo.org/test/?do=_checklist_view&document=290 et http://checklist.labocleo.org/test/?do=_checklist_view&document=634 ;
- signaler un nom complètement en majuscule comme problématique, cf. http://checklist.labocleo.org/test/?do=_checklist_view&document=365 ;
- signaler un problème quand deux noms d'auteur·rices sont stylés comme un seul, ex. "Philippe Chartier et Caroline Bornet" http://checklist.labocleo.org/test/?do=_checklist_view&document=515

**Comment by brrd** [comment]
J'isole la question de l'arabe dans #20.

**Comment by brrd** [comment]
C'est corrigé pour les majuscules et le "et"/"and". 

À l'occasion d'un nouveau ticket on pourrait envisager de différencier le surlignement entre prénom et nom de famille pour avoir un signalement plus précis, si ça te semble intéressant @amandine-texier.

**Comment by amandine-texier** [comment]
Bien vu, c'est une excellente idée ! J'ai fait le ticket :  #57
