### ISSUE TITLE
Suggestion : affichage des erreurs les plus fréquentes dans la publication

### ISSUE THREAD

**Issue by brrd** [OpenEdition/checklist-lodel#80]
En utilisant checklist je pense à une suggestion qui peut éventuellement permettre d'améliorer l'interface lors de la relecture au niveau de la publi : afficher quelque part (volet latéral ?) une liste des 5 ou 10 erreurs les plus fréquentes dans le numéro avec à chaque fois le nombre d’occurrences indiqué à côté.

Un exemple de cas de figure où c'est intéressant : je suis en  train d'importer un numéro où tous les noms d'auteurs commencent par une initiale "C. XXX", ce qui est volontaire car il s'agit de pseudonymes. J'ai donc un faux positif (dans mon cas) "Format de nom d’auteur" sur tous les articles. Après avoir corrigé toutes les autres erreurs, je relance checklist et évidemment tous mes articles apparaissent en jaune. Il faut les regarder un à un pour vérifier que la seule erreur trouvée est bien "Format de nom d’auteur".

Avec un affichage des erreurs les plus fréquentes sur la page, j'aurais pu d'un coup d'œil vérifier que "Format de nom d’auteur" était bien la seule erreur relevée dans mon numéro.

**Comment by amandine-texier** [comment]
Vu avec l'équipe : on craint que cet affichage encombre trop le template et que les utilisateurs ne regardent pas toutes les erreurs, du coup on ne préfère pas.
