### ISSUE TITLE
Organisation du projet pour Checklist Books

### ISSUE THREAD

**Issue by brrd** [OpenEdition/checklist-lodel#82]
Pour le développement du plugin Checklist pour Books, je vois deux façons d'organiser le code :

* soit on conserve un seul plugin et on ajoute une option (au niveau du site) au plugin existant checklist-lodel pour choisir entre la version "books" et la version "journals",
* soit on sépare en deux plugins, auquel cas il faudrait logiquement renommer le dépôt actuel en checklist-oej et créer un nouveau dépôt checklist-oeb.

Étant donné qu'il y aura peu de code en commun entre les deux, la 2e approche me semble la plus logique. Mais il faut surtout choisir une solution qui correspond à votre besoin.

**Comment by lnprieto** [comment]
Bonjour
La deuxième solution est en effet la plus logique et nous convient mieux.
Merci

**Comment by brrd** [comment]
Merci @lnprieto. Je n'ai pas les droits pour renommer ce dépôt. Quelqu'un chez vous pourrait-il s'en occuper ? Je me chargerai ensuite de renommer le plugin dans les fichiers.

**Comment by lnprieto** [comment]
J'ai fait la demande au service système.

**Comment by jcsouplet** [comment]
Bonjour, @brrd Si je comprends bien, l'idée est de faire un dépôt dédié à checklist-oeb car les fichiers de checklist lodel pourrait être vue comme des fichiers de config d'un plugin lodel "checklist-oej" et que le code partagé entre les deux plugins (checklist-oej et checklist-oeb) serait (et est déjà) dans le troisième dépôt "checklist". Est-ce bien cela ?

**Comment by brrd** [comment]
Oui, c'est l'idée.

Le dépôt https://github.com/OpenEdition/checklist contient une application JavaScript "générique" qui peut être utilisée dans n'importe quel contexte (Lodel ou non). Pour fonctionner elle a besoin d'une page sur laquelle s'exécuter (= ici les templates Lodelscript) et d'un fichier de configuration JS (= la liste des tests à effectuer) qui sont développés à part, actuellement dans le dépôt checklist-lodel pour OEJ.

Si on fait une version pour OEB, il y aura sans doute une petite portion de code qui sera commune avec le code spécifique à OEJ (quelque macros LodelScript et des styles CSS principalement), mais ce sera très minoritaire. Je pense qu'il y aura surtout des différences (notamment la config JS et les templates).

Côté Lodel, cela peut se traduire soit par un plugin unique qui "détecte" le contexte (OEJ ou OEB) en testant le ME et affiche le bon template avec la bonne configuration, soit par deux plugins distincts OEJ et OEB. Dans ce dernier cas je conseillerais de renommer checklist-lodel en checklist-oej, et de créer un plugin checklist-oeb, par souci de clarté.

À noter que cela implique un changement de nom de plugin Lodel, et donc le changement des URL de checklist sur OEJ.

**Comment by jcsouplet** [comment]
Ok. On propose donc de forker checklist-lodel en checklist-oej puis d'archiver checklist-lodel. Pour checklist-oeb on peut faire la même chose (fork) ou partir sur un nouveau dépôt. Que souhaites-tu ?

**Comment by jcsouplet** [comment]
l'option du double fork me semble intéressante pour suivre l'évolution du projet

**Comment by brrd** [comment]
Cette décision appartient bien sûr à OpenEdition, toutefois je suis personnellement assez défavorable à l'idée d'archiver le projet actuel pour créer un fork. Pour plusieurs raisons :

1. Nous allons devoir migrer tous les tickets un à un sur le nouveau projet.
2. Nous allons perdre l'historique des anciens tickets et des PR.
3. Le dépôt ne sera pas redirigé par Github. Ce qui veut dire que tous les nouveaux `git pull` depuis un ancien clone se solderont par un message "Already up to date" sans indiquer que le dépôt est obsolète. Dans le cas d'un renommage du projet au contraire, Github s'occupe lui-même de rediriger les requêtes vers le nouveau nom. Cela fonctionne bien, je l'ai déjà fait sur un projet avec plusieurs centaines de clones sans constater de problème.

Je recommanderais donc plutôt de renommer le dépôt, ce qui permet d'éviter tous les problèmes ci-dessus, et de passer le plugin à la version 2.0.0 pour manifester la rupture de compatibilité due au renommage (vu que le projet respecte [semver](https://semver.org/lang/fr/)).

Pour le dépôt checklist-oeb, je recommanderais de partir d'un projet vide étant donné qu'il y a peu de code en commun, et que créer un fork reviendrait donc à supprimer la quasi totalité du code du projet forké. L'historique n'aura je pense pas beaucoup de sens après ça.

Ceci étant dit et en y réfléchissant davantage, je me dis que l'idée d'avoir un plugin unique qui détecte automatiquement la nature du site (OEJ ou OEB) n'était pas si mauvaise. Je pense que ça n'est pas très compliqué à mettre en place avec le système de templates de Lodel, et ça a l'avantage de ne pas nous imposer un renommage de l'existant.

Pardon si ces dernières remarques vont dans le sens contraire de ce qui a été dit ou décidé jusqu'à présent. Je n'ai pas d'avis tranché sur la question et j'y réfléchis à mesure qu'on en parle.

Nous avons encore un peu de temps pour prendre une décision, car je ne travaillerai pas sur la version OEB avant janvier (le travail prévu en décembre ne concerne que la version pour OEJ). Si tu le souhaites nous pouvons en parler au téléphone.

**Comment by amandine-texier** [comment]
Vu aujourd'hui avec @jcsouplet, on garde un seul dépôt et on verra plus tard si c'est vraiment pertinent de diviser le projet. Si tout est bon pour toi @brrd, je te laisse fermer le ticket

**Comment by brrd** [comment]
C'est parfait, merci.
