### ISSUE TITLE
Màj du ME sur la VM ?

### ISSUE THREAD

**Issue by brrd** [OpenEdition/checklist-lodel#87]
Le ticket #71 dépend de la case à cocher "numeroouvert" qui était maquée dans le ME de la VM. Je viens de l'activer pour pouvoir travailler. Idem pour le champ "historique".

Peut-être le ME n'est-il pas à jour ? Je le signale juste au cas où, mais cela n'empêche pas le travail.

**Comment by amandine-texier** [comment]
Bien vu ! C'est bien comme ça dans notre ME de référence en fait, numeroouvert et historique sont masqués de base et affichés seulement sur les sites qui ont des numéros ouverts - je n'avais pas l'info du coup je n'ai pas pensé à le faire sur la VM.

Dans le doute j'ai vérifié les champs / types de la VM rapidement et tout semble en ordre (j'ai pas vérifié finement les paramètres des entrées mais il n'y a pas de raison que ça diffère du ME de référence)
