### ISSUE TITLE
Index Pactols non affichés

### ISSUE THREAD

**Issue by amandine-texier** [OpenEdition/checklist-lodel#92]
Les index Pactols, utilisés notamment dans les types de textes "noticearcheologique", ne s'affichent pas dans le template Checklist, ex. : http://checklist.labocleo.org/test/?do=_checklist_view&document=919 

C'est de ma faute : je ne comprenais pas bien le fonctionnement de ces index à l'époque de la rédaction du cahier des charges. Il se trouve que c'est une autre classe d'index "pactols" avec six types d'index :

- sujets
- lieux
- anthroponymes
- oeuvres
- chronologie
- peuple

Est-il possible d'ajouter ces index aux templates articles, quand ils existent dans le ME ? En effet, ils ne seront installés que sur des sites qui utilisent ces index d'archéo. Ils seront également nécessaires sur des sites Books.

**Comment by brrd** [comment]
Attention aux erreurs SQL, cette classe n'est pas présente sur tous les sites.

**Comment by brrd** [comment]
C'est ajouté. J'ai également désactivé les règles de composition des index et de doublons sur ces index.

@amandine-texier Est-il nécessaire d'ajouter un onglet sur la home pour ces index, sachant qu'aucune règle ne s'applique à eux ?

**Comment by amandine-texier** [comment]
Je ne sais pas si j'ai raté quelque chose mais je ne vois toujours pas les index s'afficher sur le template Checklist : http://checklist.labocleo.org/test/?do=_checklist_view&document=919
J'ai vidé mon cache pourtant

Effectivement, pas nécessaire d'afficher l'index sur la home, et merci d'avoir désactivé les règles dessus.

**Comment by brrd** [comment]
C'est corrigé, le code n'était pas à jour sur la VM. Je me suis sans doute emmêlé dans mes branches git.

**Comment by brrd** [comment]
Il faut utiliser le champ MLNOM pour afficher ces index.

**Comment by brrd** [comment]
J'ai ajouté l'affichage des nom des index pactols. Contrairement aux autres entités dans Lodel, ces index n'ont qu'un nom multilingue, et pas de nom principal sur lequel je pourrais me rabattre quand le nom dans la langue du site n'existe pas. Donc lorsque le nom n'existe pas dans la langue d'affichage du site, c'est l'identifiant qui est affiché.

Voir ici un exemple avec une entrée qui n'a qu'un nom en anglais (et pas en français) : 

![image](https://user-images.githubusercontent.com/7335302/114045349-3eb5ad00-9888-11eb-9f39-274e0646763b.png)

**Comment by amandine-texier** [comment]
C'est parfait ainsi, merci !
Les personnes qui utilisent ces index sont au courant des manques dans les traductions donc je pense que ça ne sera pas gênant. Comme tout est bon pour ces index, je clos le ticket
