### ISSUE TITLE
Comment reconnaitre un ME books ?

### ISSUE THREAD

**Issue by brrd** [OpenEdition/checklist-lodel#94]
Étant donné que le plugin Checklist sera le même pour OEJ et OEB, il faut que l'on puisse identifier la plateforme dans les templates. Le mieux est sans doute de tester les champs du ME du site.

Comment feriez-vous pour reconnaître un ME de livre (par exemple : tester l'existence du type livre de la classe publications) ? J'imagine qu'il y a des tonnes de façons de faire ça, mais je préfère demander celle qui vous semble la meilleure.

Dans le cas où cette condition échoue, Checklist considèrera qu'il s'agit d'un ME de revue.

**Comment by amandine-texier** [comment]
Ton hypothèse de tester l'existence du type livre de la classe publications se trouve être la meilleure option : normalement nous n'avons plus ce type sur OEJ et il est bien entendu présent sur tous les sites OEB !

**Comment by brrd** [comment]
Super, ça répond à ma question, merci.
