### ISSUE TITLE
Adaptation du template article au ME OEB

### ISSUE THREAD

**Issue by brrd** [OpenEdition/checklist-lodel#95]
Voici le template article (presque) sans modification, appliqué sur un site books : https://books-devel.labocleo.org/africae/index.php?id=2017

@amandine-texier Pourrais-tu stp recenser les choses qui ne vont pas sur ce template (champs manquants, présentations erronées, etc.) ? Sans prendre en compte les règles qui devront changer de toute façon. L'idée pour l'instant est de se concentrer sur les templates.

Je vois par exemple que le fil d’Ariane ne mentionne pas le livre parent.

Tu m'avais également donné les champs suivants à ajouter : **EDIT: cf plus bas**

Est-ce que tu vois autre chose ? Avez-vous un document "tous les styles" pour Books qui permettrait de vérifier que tous les champs fonctionnent bien ?

# EDIT: TODO

Books + revues :

* [x] Pour le type "informations" il faudrait renvoyer sur la home.
* [x] Ne pas afficher le plan de l'article s'il est vide.
* [x] Déplacer "Texte au format PDF" dans le cartouche

Books uniquement : 

* [x] Ajouter les types : 
  - surtitre
  - langueoriginale (cartouche)
  - sujets
  - lieux
  - anthroponymes
  - oeuvres
  - chronologie
  - peuple
  - nature
* [x] Il faudrait supprimer la mention "barrière mobile" qui n'existe pas sur OEB
* [x] L'index "Personnes citées" ne s'affiche pas.
* [x] Ne pas numéroter les paragraphes des textes de type "index" et "bibliographie". Index : https://books-devel.labocleo.org/africae/?do=_checklist_view&document=1037#ftn1 Biblio : https://books-devel.labocleo.org/africae/?do=_checklist_view&document=2381
* [x] Le type "adressebibliographique" doit être masqué partout (Arianne, templates, tests).

**Comment by amandine-texier** [comment]
C'est déjà très propre !
Je ne sais pas si tu as fais des modifications depuis mais j'ai l'impression que le livre parent s'affiche bien dans le fil d'Ariane (idem pour la collection). 

J'ai chargé une UE avec tous les styles : https://books-devel.labocleo.org/africae/index.php?id=2353

Il faudrait supprimer la mention "barrière mobile" qui n'existe pas sur OEB
L'index "Personnes citées" ne s'affiche pas.
Est-ce que "Texte au format PDF" pourrait apparaître dans le cartouche ?

Pour les documents sans intertitre, ex. https://books-devel.labocleo.org/africae/?do=_checklist_view&document=1432, est-ce envisageable de ne pas afficher le "Plan", qui est vide du coup ?

Petite particularité d'OEB, pour les types "index" et "bibliographie", les paragraphes ne sont pas numérotés dans la maquette. Est-ce possible de faire de même sur le templates Checklist juste pour ces deux types ? Un index : https://books-devel.labocleo.org/africae/?do=_checklist_view&document=1037#ftn1 et une biblio : https://books-devel.labocleo.org/africae/?do=_checklist_view&document=2381

Et je m'excuse de revenir sur ce que j'ai dit, mais finalement je ne pense pas qu'il soit intéressant d'ajouter les index PACTOLS (sujets, lieux, anthroponymes, oeuvres, chronologie, peuple, nature) ou les métadonnées archéo (collaborateur, directeurfouilles). Vu le retard pris sur l'ajout de ces méta sur la plateforme en prod, ça risque de ne pas se faire avant la migration sous symfony donc autant gagner du temps là-dessus pour l'instant.

Au niveau des types de la classe textes sur OEB : il faudrait que "adressebibliographique" soit exclu des tests (c'est un type qu'on utilise seulement pour archive pour la vérification des livres issus du soutien à numérisation) et renvoie sur le parent (le livre) si possible, sinon sur la home. Du coup ce document ne doit pas non plus faire partie du fil d'Ariane ou être récupéré sur le template publications.

Pour le type "informations" il faudrait renvoyer sur la home.
(Mais c'est peut-être pas le bon endroit pour ces notes, dis moi si je créé un ticket à part)

**Comment by brrd** [comment]
> Je ne sais pas si tu as fais des modifications depuis mais j'ai l'impression que le livre parent s'affiche bien dans le fil d'Ariane (idem pour la collection).

Au temps pour moi.

Je créé une liste de tâches dans le premier commentaire de ce fil et j'y ajouterai test demandes petit à petit pour que rien ne se perde.

>   Est-ce que "Texte au format PDF" pourrait apparaître dans le cartouche ?

Pour la version journals, cette info n'apparaît pas dans le cartouche. Est-ce qu'il serait à tout hasard possible d'adopter une présentation commune aux deux plateformes ?

Ce type de divergence est tout à faire possible, mais il faut avoir à l'esprit que ça rend le code moins lisible (et complique éventuellement son évolution) donc je recommanderais de les limiter au maximum quand c'est possible.

> Pour les documents sans intertitre, ex. https://books-devel.labocleo.org/africae/?do=_checklist_view&document=1432, est-ce envisageable de ne pas afficher le "Plan", qui est vide du coup ?

Je pense que c'est également applicable aux revues, non ?

> Et je m'excuse de revenir sur ce que j'ai dit, mais finalement je ne pense pas qu'il soit intéressant d'ajouter les index PACTOLS (sujets, lieux, anthroponymes, oeuvres, chronologie, peuple, nature) ou les métadonnées archéo (collaborateur, directeurfouilles). Vu le retard pris sur l'ajout de ces méta sur la plateforme en prod, ça risque de ne pas se faire avant la migration sous symfony donc autant gagner du temps là-dessus pour l'instant.

Si les index ne sont pas présents (dans le ME et associés à l'article) alors ils ne s'afficheront pas. Est-ce qu'il est quand même nécessaire de les supprimer ?

> Pour le type "informations" il faudrait renvoyer sur la home.

Je vais le faire également pour les revues où cela s'applique aussi il me semble.

>  (Mais c'est peut-être pas le bon endroit pour ces notes, dis moi si je créé un ticket à part)

Ça risque d'être lourd si on créé un ticket par demande à ce stade. Je propose de dégrossir ici dans un premier temps, puis de passer sur des tickets quand on avancera dans les détails.

**Comment by amandine-texier** [comment]
> Pour la version journals, cette info n'apparaît pas dans le cartouche. Est-ce qu'il serait à tout hasard possible d'adopter une présentation commune aux deux plateformes ?

Tout à fait, je n'avais pas fait attention mais c'est plus cohérent que ce champs apparaisse dans le cartouche, sur Journals et Books. Et je suis tout à fait d'accord qu'il faut que la présentation / le fonctionnement soient communs à chaque fois que c'est possible.

Effectivement c'est le même principe pour le plan vide, il faudrait qu'il ne s'affiche pas sur les deux plateformes.

> Si les index ne sont pas présents (dans le ME et associés à l'article) alors ils ne s'afficheront pas. Est-ce qu'il est quand même nécessaire de les supprimer ?

Non, c'est parfait, pas besoin de les supprimer.

> Je vais le faire également pour les revues où cela s'applique aussi il me semble.

Tout à fait, merci

> Ça risque d'être lourd si on créé un ticket par demande à ce stade. Je propose de dégrossir ici dans un premier temps, puis de passer sur des tickets quand on avancera dans les détails.

Entendu c'est parfait pour moi !

**Comment by brrd** [comment]
J'ai effectué l'ensemble de ces modifs. 

Pour les index à ajouter, il s'agit bien des pactols (déjà ajouté donc) ?

J'ai ajouté les personnes citées à la suite des auteurs, traducteurs etc. avec la même présentation. On peut les déplacer si nécessaire, et éventuellement utiliser une présentation en liste moins détaillée (à confirmer).
Pour info, cet index est vide sur la VM : https://books-devel.labocleo.org/africae/lodel/admin/index.php?do=list&lo=persons&idtype=245

Le type "adressebibliographique" se comporte maintenant comme les informations et actualités : on renvoie vers le parent s'il existe, sinon vers la home.

Est-ce que tu vois autre chose à corriger @amandine-texier ?

**Comment by amandine-texier** [comment]
Merci pour toutes les modifs ! 
Oui pour les index c'est parfait, tout y est et pour le type adressebibliographique tout fonctionne comme attendu.

Il y avait un soucis au niveau du ME du site (je ne sais pas d'où ça peut venir d'ailleurs) du coup les personnes citées que j'avais renseignées sur le document s'étaient pas importées, l'index apparait bien maintenant : https://books-devel.labocleo.org/africae/?do=_checklist_view&document=2353

Je pense qu'en liste comme au niveau du livre (cf. https://books-devel.labocleo.org/africae/?do=_checklist_view&document=847) ce serait bien, et si on pouvait déplacer les personnes citées dans le bloc "index", après l'index thématique ce serait top.

D'ailleurs je remarque que la pagination apparaît à la fin de ce bloc (sur OEJ et OEB) et je pense qu'il faudrait la déplacer dans la section Métadonnées en tout premier avant "numerodocument", c'est possible ? Comme ça on trouve la pagination juste après les auteurs et autrices, ça se rapproche de l'affichage HTML et du modèle de style.

**Comment by brrd** [comment]
C'est fait.

**Comment by amandine-texier** [comment]
Tout est parfait merci je ferme le ticket
