### ISSUE TITLE
Affichage livre

### ISSUE THREAD

**Issue by brrd** [OpenEdition/checklist-lodel#97]
J'ai fait fonctionner le template des publications sur les livres : https://books-devel.labocleo.org/africae/?do=_checklist_view&document=2009

Les champs à ajouter sont les suivants : 

* [x] auteur
* [x] traducteur
* [x] editeurscientifique
* [x] languesecondaire (cartouche)
* [x] langueoriginale (cartouche)
* [x] anneeedition
* [x] lieuedition
* [x] nombrepages
* [x] coediteur
* [x] index.1337 (licence)
* [x] funder
* [x] resume
* [x] extrait
* [x] isbnhtml
* [x] motsclesfr
* [x] motsclesen
* [x] motscleses
* [x] motslcespt
* [x] motsclesit
* [x] motsclesde
* [x] dossiers
* [x] chrono
* [x] geographie
* [x] theme
* [x] personnecitee
* [x] ocr : "cartouche" ; si coché, afficher "Cette publication est issue d'une reconnaissance automatique de caractères."

Comme convenu, ces champs seront affichés pour les livres **et les revues** quand ils existent et ne sont pas vides. Si l'équipe des revues souhaite que certains de ces champs n'apparaissent jamais sur OEJ (je pense par exemple aux différents index de mots-clés, qui existent parfois sur les publications des revues) alors il faudra me le signaler pour que j'ajoute des conditions d'affichage.

Réciproquement, il y a aura peut-être des champs des revues à supprimer de l'affichage des livres.

@amandine-texier Je te laisse me faire un retour sur cette première version et me dire si tu vois d'autres modifications à ajouter à la liste.

**Comment by brrd** [comment]
J'ai ajouté les champs des livres au template des publications, sauf "licence" qui est un index mutualisé, plus compliqué.

Je n'ai rien supprimé des champs des revues, je préfère te laisse me dire ce qui n'est pas pertinent sur OEB.

Actuellement le tout est un peu en bazar, il est possible de retrier les éléments, voire les regrouper dans des sections si besoin. Pour voir tous les champs actuellement affichés ici (journals et books confondu), c'est ici : https://github.com/OpenEdition/checklist-lodel/blob/43537548cb4614352346520b12a9ecd7801302be/tpl/macros_checklist_publication.html#L102

Pour l'index de licence, @amandine-texier pourrais-tu me donner un exemple de résultat attendu (sur une page de livre sur OEB par exemple). En lisant le code de la lodelia books, j'ai l'impression que la licence peut-être définie à plusieurs niveaux différents (livre, éditeur). Est-ce bien ça ? Le cas échéant, faut-il gérer l'héritage et récupérer la licence définie au niveau de l'éditeur lorsqu'elle n'existe pas au niveau du livre ?

N'hésite pas à me donner tes retours.

**Comment by amandine-texier** [comment]
Merci pour toutes ces modifs, ça fait plaisir à voir !

Pour l'index des licences, voici un exemple d'affichage sur un livre : https://books.openedition.org/obp/16312 "Creative Commons - Attribution 4.0 International - CC BY 4.0" et la même sur une UE : https://books.openedition.org/obp/16447 (par héritage du livre du coup). Il y a effectivement un système d'héritage au niveau de la notice éditeur, quand rien n'est renseigné au niveau du livre. Et si rien n'est renseigné dans aucun des deux c'est la licence "OpenEdition Licence for Books" qui s'applique (qui correspond au droit d'auteur classique).

Le fonctionnement est comme pour les index Pactols, le nom de l'entrée c'est "CC BY 4.0" et le mlnom "Creative Commons - Attribution 4.0 International - CC BY 4.0" mais ici récupérer le nom de l'entrée serait amplement suffisant. 

Pour le template publication, je vois plusieurs champs à supprimer de Books qui sont pertinents seulement pour Journals : 

- [ ] datepubli
- [ ] datepublipapier
- [ ] paraitre
- [ ] datemisenligne
- [ ] dateacceslibre
- [ ] integralite
- [ ] introduction (sur OEB utilisé seulement pour les collections, autrement n'apparaît pas)

Est-il possible de rajouter le champ description d'auteur quand il est renseigné au niveau livre ? Pour tous les types d'auteurs, directeurs, éditeurs scientifiques, traducteurs, auteurs...

Et petite subtilité pour les champs résumé / extrait : l'extrait est utilisé seulement en l'absence d'un résumé ; du coup si le champ résumé est renseigné, est-ce possible de ne pas afficher l'extrait, même s'il contient du texte ? Mais de l'afficher si résumé est vide ?

J'ai complété un livre pour l'exemple : https://books-devel.labocleo.org/africae/?do=_checklist_view&document=847

Je veux bien revérifier tout ça une fois les changements faits, voir si on peut faire des regroupements ou non pour rendre tout ça plus clair

**Comment by brrd** [comment]
Pour les licences, voir #99. Pour l'instant j'arrive à récupérer la licence au niveau du livre, mais pas au niveau de l'éditeur (ou en tout cas ça ne fonctionne pas sur la VM).

> Pour le template publication, je vois plusieurs champs à supprimer de Books qui sont pertinents seulement pour Journals : [...]

Ces champs sont-ils renseignés sur OEB ? S'ils sont vides (ou n'existent pas) alors il n'est pas utile de les supprimer car ils ne s'afficheront pas de toute façon.

> Est-il possible de rajouter le champ description d'auteur quand il est renseigné au niveau livre ? Pour tous les types d'auteurs, directeurs, éditeurs scientifiques, traducteurs, auteurs...

Les types de personnes disponibles sont :  Auteurs  |  Traducteurs  |  Directeurs de la publication  |  Éditeurs scientifiques  |  Personnes citées

Actuellement la description est déjà affichée pour : auteur, traducteur, editeurscientifique
Seuls les noms sont affichés pour : directeurdelapublication, personnecitee
Peux-tu me confirmer que la seule modification à faire est d'ajouter la description des directeurdelapublication ?

> Et petite subtilité pour les champs résumé / extrait : l'extrait est utilisé seulement en l'absence d'un résumé ; du coup si le champ résumé est renseigné, est-ce possible de ne pas afficher l'extrait, même s'il contient du texte ? Mais de l'afficher si résumé est vide ?

C'est fait.

**Comment by amandine-texier** [comment]
Je vais demander de l'aide pour la question des licences.

Je confirme que les champs mentionnés sont renseignés (automatiquement) sur Books : du coup ils apparaissent sur Checklist et risquent de perturber les utilisateurs, si on peut les masquer ce serait parfait.

Et pour la description d'auteur, effectivement la seule modification à faire est d'ajouter l'affichage pour les directeurdelapublication

**Comment by amandine-texier** [comment]
Je viens de réaliser, est-ce possible également de déplacer le champ "ISBN HTML" dans le cartouche ? (Comme il ne s'affiche pas dans la maquette Books, ce serait plus cohérent)

**Comment by brrd** [comment]
> Est-il possible de rajouter le champ description d'auteur quand il est renseigné au niveau livre ? Pour tous les types d'auteurs, directeurs, éditeurs scientifiques, traducteurs, auteurs...

Fait.

**Comment by amandine-texier** [comment]
Je fais un bilan ici de ce qu'il faudrait modifier sur le template livre suite à nos discussions et aux retours en interne : 

- [ ] pour la licence, la récupérer seulement si elle est renseignée au niveau du livre sinon ne rien afficher ;
- [ ] déplacer le champ "ISBN HTML" dans le cartouche, après la langue ;
- [ ] serait-il possible d'afficher les entrées des champs "index.49", "index.73" et "index.70" dans le cartouche après l'ISBN HTML quand ils sont renseignés ? Ces champs n'existent pas niveau publications sur OEJ ;
- [ ] masquer sur le template OEB les champs datepubli, datepublipapier, paraitre, datemisenligne, dateacceslibre, integralite, introduction qui existent sur OEB mais n'ont pas d'incidence.

Avec ça, normalement le template livre sera finalisé !

**Comment by brrd** [comment]
C'est fait. 

Je ferme ce ticket qui commence à devenir illisible. @amandine-texier je te laisse vérifier et ouvrir de nouveaux tickets s'il y a des choses à corriger.
