### ISSUE TITLE
Home adaptée aux livres

### ISSUE THREAD

**Issue by brrd** [OpenEdition/checklist-lodel#98]
J'ai adapté la home à l'affichage des livres : https://books-devel.labocleo.org/africae/?do=_checklist_view

Pour faire simple, le premier onglet affiche maintenant les numéros et les livres (mais ces types n'existent normalement jamais tous les deux en même temps sur un site). J'ai renommé l'onglet "Publications" pour que cela s'applique à toutes les situations.

J'ai aussi ajouté les livres aux types supportés par l'export CSV. Normalement cela devrait fonctionner.

@amandine-texier N'hésite pas à me donner tes retours.

**Comment by amandine-texier** [comment]
Merci !

Des retours **seulement pour OEB** : 
Est-ce possible d'ajouter un filtre au niveau de l'onglet "Publications" permettant de sélectionner une collection particulière ?

Et est-ce envisageable que ces filtres (collection + publié / non publié, cf. #103) puissent fonctionner ensemble ? Par exemple sélectionner les livres non publiés de la collection "Africae Studies" ?

Dans l'affichage des publications, il faudrait supprimer le numéro du document actuellement présent (ex. "15 | Indian Africa") pour ne conserver que le titre.

Au niveau de l'onglet "Export CSV", est-ce possible de masquer "Activer le filtre "Publication papier" ? Ou à défaut si ce n'est pas possible, de s'assurer qu'il n'aura pas d'impact sur les exports, qu'il soit coché ou décoché.

Une petite question : je vois que les index géographiques et chronologiques (qui ont pourtant des entrées renseignées) ne s'affichent pas dans l'onglet "Index", est-ce parce que toutes les entrées sont non publiées ? Si c'est le cas c'est cohérent avec le fonctionnement de Lodel donc ce n'est pas du tout gênant mais c'est pour avoir l'info.

**Comment by brrd** [comment]
> Une petite question : je vois que les index géographiques et chronologiques (qui ont pourtant des entrées renseignées) ne s'affichent pas dans l'onglet "Index", est-ce parce que toutes les entrées sont non publiées ?

Sans doute. Je pense que Lodel gère ça comme ça par défaut. Il faudrait faire le test pour s'en assurer, et je dois pouvoir inclure les index non publiés si besoin (à confirmer).

**Comment by amandine-texier** [comment]
> Sans doute. Je pense que Lodel gère ça comme ça par défaut. Il faudrait faire le test pour s'en assurer, et je dois pouvoir inclure les index non publiés si besoin (à confirmer).

Je viens de tester et je confirme que si on publie un document avec une entrée dans un de ces index, ils apparaissent alors dans la home de Checklist : comme ça correspond au comportement de Lodel c'est parfait pour moi !

**Comment by brrd** [comment]
* [ ] Ajout d'un filtre collection sur l'onglet Publications
* [ ] Ajout d'un filtre statut sur l'onglet Publications
* [ ] Suppression du champ "numero" dans le titre des publications sur OEB
* [x] Suppression de l'option displayPaper dans l'export CSV (#102)

**Comment by brrd** [comment]
> Ajout d'un filtre collection sur l'onglet Publications

@amandine-texier Peux-tu me confirmer que les livres (et les numéros) sont toujours directement enfants des collections, sans publications intermédiaires. Autrement dit, qu'on a toujours la structure : collection > livre (ou collection > numéro), et jamais : collection > xxx > livre ?

**Comment by brrd** [comment]
C'est fait sur la VM books. Mais je veux bien la confirmation de la question précédente quand même.

**Comment by amandine-texier** [comment]
C'est parfait pour Books ! Et ça fonctionne effectivement selon la structure collection > livre et collection > numéro
