### ISSUE TITLE
Fonctionnement de la loop_solr() sur books-devel

### ISSUE THREAD

**Issue by brrd** [OpenEdition/checklist-lodel#99]
Je n'arrive pas à faire fonctionner la LOOP suivante sur la VM (code copié ici depuis votre maquette de livre, qui devrait donc normalement fonctionner) : 

```html
<LET VAR="solrplateform">OB</LET>
<LET VAR="myquery">platformID:"[#SOLRPLATEFORM]" AND pubentry_publication:"[#SITE]"</LET>
<LOOP NAME="SOLR" QUERY="[#MYQUERY]" ROWS="1" CORE="publishers" FIELDS="pub_titre,pubentry_licence">
	<LET ARRAY="mysite.titre" GLOBAL="1">[#PUB_TITRE]</LET>
	<LET ARRAY="mysite.licence" GLOBAL="1">[#PUBENTRY_LICENCE.0]</LET>
</LOOP>
```

Ici la valeur `[%MYSITE.LICENCE]` est toujours vide, même en modifiant la notice de site pour y qu'il y ait une valeur.

Ça pourrait expliquer que l'héritage de licence ne fonctionne apparemment pas sur les pages publiques de la VM : https://books-devel.labocleo.org/africae/index.php?id=2342&clearcache=oui

Pour un exemple d'utilisation réelle, voir 6b8a104999e36c8aad1b12148e013c43ddbc200f (et s'il y a une autre façon de faire je suis preneur).

**Comment by amandine-texier** [comment]
Vu avec les collègues : en fait le calcul de la licence n'est fait que dans Core pour l'instant, et le système des licences sera revu d'ici 2022, du coup on peut aller au plus simple ici : récupérer la licence seulement si elle est renseigné au niveau du livre, merci
